/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeleteV1TmuxPanesPaneID200,
  DeleteV1TmuxSessionsSessionName200,
  GetV1TmuxPanesParams,
  GetV1TmuxWindowsParams,
  PostV1TmuxSessionsCreate200,
  PostV1TmuxSessionsCreateBody,
  TmuxClientInternalTypesAPIError,
  TmuxClientInternalTypesCreatePaneRequest,
  TmuxClientInternalTypesCreatePaneResponse,
  TmuxClientInternalTypesKillSessionResponse,
  TmuxClientInternalTypesListPanesResponse,
  TmuxClientInternalTypesReadPaneRequest,
  TmuxClientInternalTypesReadPaneResponse,
  TmuxClientInternalTypesSendKeysRequest,
  TmuxClientInternalTypesSendKeysResponse,
  TmuxClientInternalTypesSessionInfo,
  TmuxClientInternalTypesSwitchPaneRequest,
  TmuxClientInternalTypesSwitchPaneResponse,
  TmuxClientInternalTypesWindowInfo
} from '.././model';





/**
 * Get a list of panes in a tmux session
 * @summary List tmux panes
 */
export const getV1TmuxPanes = (
    params?: GetV1TmuxPanesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesListPanesResponse>> => {
    
    
    return axios.default.get(
      `/v1/tmux/panes`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetV1TmuxPanesQueryKey = (params?: GetV1TmuxPanesParams,) => {
    return [
    `/v1/tmux/panes`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetV1TmuxPanesQueryOptions = <TData = Awaited<ReturnType<typeof getV1TmuxPanes>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(params?: GetV1TmuxPanesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxPanes>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1TmuxPanesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1TmuxPanes>>> = ({ signal }) => getV1TmuxPanes(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxPanes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1TmuxPanesQueryResult = NonNullable<Awaited<ReturnType<typeof getV1TmuxPanes>>>
export type GetV1TmuxPanesQueryError = AxiosError<TmuxClientInternalTypesAPIError>


export function useGetV1TmuxPanes<TData = Awaited<ReturnType<typeof getV1TmuxPanes>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 params: undefined |  GetV1TmuxPanesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxPanes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1TmuxPanes>>,
          TError,
          Awaited<ReturnType<typeof getV1TmuxPanes>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1TmuxPanes<TData = Awaited<ReturnType<typeof getV1TmuxPanes>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 params?: GetV1TmuxPanesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxPanes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1TmuxPanes>>,
          TError,
          Awaited<ReturnType<typeof getV1TmuxPanes>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1TmuxPanes<TData = Awaited<ReturnType<typeof getV1TmuxPanes>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 params?: GetV1TmuxPanesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxPanes>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List tmux panes
 */

export function useGetV1TmuxPanes<TData = Awaited<ReturnType<typeof getV1TmuxPanes>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 params?: GetV1TmuxPanesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxPanes>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1TmuxPanesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Kills a tmux pane
 * @summary Kill tmux pane
 */
export const deleteV1TmuxPanesPaneID = (
    paneID: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteV1TmuxPanesPaneID200>> => {
    
    
    return axios.default.delete(
      `/v1/tmux/panes/${paneID}`,options
    );
  }



export const getDeleteV1TmuxPanesPaneIDMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1TmuxPanesPaneID>>, TError,{paneID: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1TmuxPanesPaneID>>, TError,{paneID: string}, TContext> => {

const mutationKey = ['deleteV1TmuxPanesPaneID'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1TmuxPanesPaneID>>, {paneID: string}> = (props) => {
          const {paneID} = props ?? {};

          return  deleteV1TmuxPanesPaneID(paneID,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1TmuxPanesPaneIDMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1TmuxPanesPaneID>>>
    
    export type DeleteV1TmuxPanesPaneIDMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Kill tmux pane
 */
export const useDeleteV1TmuxPanesPaneID = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1TmuxPanesPaneID>>, TError,{paneID: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1TmuxPanesPaneID>>,
        TError,
        {paneID: string},
        TContext
      > => {

      const mutationOptions = getDeleteV1TmuxPanesPaneIDMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a new tmux pane
 * @summary Create tmux pane
 */
export const postV1TmuxPanesCreate = (
    tmuxClientInternalTypesCreatePaneRequest: TmuxClientInternalTypesCreatePaneRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesCreatePaneResponse>> => {
    
    
    return axios.default.post(
      `/v1/tmux/panes/create`,
      tmuxClientInternalTypesCreatePaneRequest,options
    );
  }



export const getPostV1TmuxPanesCreateMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxPanesCreate>>, TError,{data: TmuxClientInternalTypesCreatePaneRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxPanesCreate>>, TError,{data: TmuxClientInternalTypesCreatePaneRequest}, TContext> => {

const mutationKey = ['postV1TmuxPanesCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1TmuxPanesCreate>>, {data: TmuxClientInternalTypesCreatePaneRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1TmuxPanesCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1TmuxPanesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postV1TmuxPanesCreate>>>
    export type PostV1TmuxPanesCreateMutationBody = TmuxClientInternalTypesCreatePaneRequest
    export type PostV1TmuxPanesCreateMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Create tmux pane
 */
export const usePostV1TmuxPanesCreate = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxPanesCreate>>, TError,{data: TmuxClientInternalTypesCreatePaneRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1TmuxPanesCreate>>,
        TError,
        {data: TmuxClientInternalTypesCreatePaneRequest},
        TContext
      > => {

      const mutationOptions = getPostV1TmuxPanesCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Reads the content of a tmux pane
 * @summary Read tmux pane
 */
export const postV1TmuxPanesRead = (
    tmuxClientInternalTypesReadPaneRequest: TmuxClientInternalTypesReadPaneRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesReadPaneResponse>> => {
    
    
    return axios.default.post(
      `/v1/tmux/panes/read`,
      tmuxClientInternalTypesReadPaneRequest,options
    );
  }



export const getPostV1TmuxPanesReadMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxPanesRead>>, TError,{data: TmuxClientInternalTypesReadPaneRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxPanesRead>>, TError,{data: TmuxClientInternalTypesReadPaneRequest}, TContext> => {

const mutationKey = ['postV1TmuxPanesRead'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1TmuxPanesRead>>, {data: TmuxClientInternalTypesReadPaneRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1TmuxPanesRead(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1TmuxPanesReadMutationResult = NonNullable<Awaited<ReturnType<typeof postV1TmuxPanesRead>>>
    export type PostV1TmuxPanesReadMutationBody = TmuxClientInternalTypesReadPaneRequest
    export type PostV1TmuxPanesReadMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Read tmux pane
 */
export const usePostV1TmuxPanesRead = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxPanesRead>>, TError,{data: TmuxClientInternalTypesReadPaneRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1TmuxPanesRead>>,
        TError,
        {data: TmuxClientInternalTypesReadPaneRequest},
        TContext
      > => {

      const mutationOptions = getPostV1TmuxPanesReadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Sends keystrokes to a tmux pane
 * @summary Send keys to tmux pane
 */
export const postV1TmuxPanesSendKeys = (
    tmuxClientInternalTypesSendKeysRequest: TmuxClientInternalTypesSendKeysRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesSendKeysResponse>> => {
    
    
    return axios.default.post(
      `/v1/tmux/panes/send-keys`,
      tmuxClientInternalTypesSendKeysRequest,options
    );
  }



export const getPostV1TmuxPanesSendKeysMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxPanesSendKeys>>, TError,{data: TmuxClientInternalTypesSendKeysRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxPanesSendKeys>>, TError,{data: TmuxClientInternalTypesSendKeysRequest}, TContext> => {

const mutationKey = ['postV1TmuxPanesSendKeys'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1TmuxPanesSendKeys>>, {data: TmuxClientInternalTypesSendKeysRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1TmuxPanesSendKeys(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1TmuxPanesSendKeysMutationResult = NonNullable<Awaited<ReturnType<typeof postV1TmuxPanesSendKeys>>>
    export type PostV1TmuxPanesSendKeysMutationBody = TmuxClientInternalTypesSendKeysRequest
    export type PostV1TmuxPanesSendKeysMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Send keys to tmux pane
 */
export const usePostV1TmuxPanesSendKeys = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxPanesSendKeys>>, TError,{data: TmuxClientInternalTypesSendKeysRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1TmuxPanesSendKeys>>,
        TError,
        {data: TmuxClientInternalTypesSendKeysRequest},
        TContext
      > => {

      const mutationOptions = getPostV1TmuxPanesSendKeysMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Switches to a specific tmux pane
 * @summary Switch tmux pane
 */
export const postV1TmuxPanesSwitch = (
    tmuxClientInternalTypesSwitchPaneRequest: TmuxClientInternalTypesSwitchPaneRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesSwitchPaneResponse>> => {
    
    
    return axios.default.post(
      `/v1/tmux/panes/switch`,
      tmuxClientInternalTypesSwitchPaneRequest,options
    );
  }



export const getPostV1TmuxPanesSwitchMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxPanesSwitch>>, TError,{data: TmuxClientInternalTypesSwitchPaneRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxPanesSwitch>>, TError,{data: TmuxClientInternalTypesSwitchPaneRequest}, TContext> => {

const mutationKey = ['postV1TmuxPanesSwitch'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1TmuxPanesSwitch>>, {data: TmuxClientInternalTypesSwitchPaneRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1TmuxPanesSwitch(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1TmuxPanesSwitchMutationResult = NonNullable<Awaited<ReturnType<typeof postV1TmuxPanesSwitch>>>
    export type PostV1TmuxPanesSwitchMutationBody = TmuxClientInternalTypesSwitchPaneRequest
    export type PostV1TmuxPanesSwitchMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Switch tmux pane
 */
export const usePostV1TmuxPanesSwitch = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxPanesSwitch>>, TError,{data: TmuxClientInternalTypesSwitchPaneRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1TmuxPanesSwitch>>,
        TError,
        {data: TmuxClientInternalTypesSwitchPaneRequest},
        TContext
      > => {

      const mutationOptions = getPostV1TmuxPanesSwitchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get a list of all active tmux sessions
 * @summary List tmux sessions
 */
export const getV1TmuxSessions = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesSessionInfo[]>> => {
    
    
    return axios.default.get(
      `/v1/tmux/sessions`,options
    );
  }




export const getGetV1TmuxSessionsQueryKey = () => {
    return [
    `/v1/tmux/sessions`
    ] as const;
    }

    
export const getGetV1TmuxSessionsQueryOptions = <TData = Awaited<ReturnType<typeof getV1TmuxSessions>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxSessions>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1TmuxSessionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1TmuxSessions>>> = ({ signal }) => getV1TmuxSessions({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1TmuxSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1TmuxSessions>>>
export type GetV1TmuxSessionsQueryError = AxiosError<TmuxClientInternalTypesAPIError>


export function useGetV1TmuxSessions<TData = Awaited<ReturnType<typeof getV1TmuxSessions>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1TmuxSessions>>,
          TError,
          Awaited<ReturnType<typeof getV1TmuxSessions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1TmuxSessions<TData = Awaited<ReturnType<typeof getV1TmuxSessions>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1TmuxSessions>>,
          TError,
          Awaited<ReturnType<typeof getV1TmuxSessions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1TmuxSessions<TData = Awaited<ReturnType<typeof getV1TmuxSessions>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxSessions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List tmux sessions
 */

export function useGetV1TmuxSessions<TData = Awaited<ReturnType<typeof getV1TmuxSessions>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxSessions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1TmuxSessionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Releases (kills) a tmux session by ID
 * @summary Release tmux session
 */
export const postV1TmuxSessionsSessionIdRelease = (
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesKillSessionResponse>> => {
    
    
    return axios.default.post(
      `/v1/tmux/sessions/${sessionId}/release`,undefined,options
    );
  }



export const getPostV1TmuxSessionsSessionIdReleaseMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxSessionsSessionIdRelease>>, TError,{sessionId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxSessionsSessionIdRelease>>, TError,{sessionId: string}, TContext> => {

const mutationKey = ['postV1TmuxSessionsSessionIdRelease'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1TmuxSessionsSessionIdRelease>>, {sessionId: string}> = (props) => {
          const {sessionId} = props ?? {};

          return  postV1TmuxSessionsSessionIdRelease(sessionId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1TmuxSessionsSessionIdReleaseMutationResult = NonNullable<Awaited<ReturnType<typeof postV1TmuxSessionsSessionIdRelease>>>
    
    export type PostV1TmuxSessionsSessionIdReleaseMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Release tmux session
 */
export const usePostV1TmuxSessionsSessionIdRelease = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxSessionsSessionIdRelease>>, TError,{sessionId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1TmuxSessionsSessionIdRelease>>,
        TError,
        {sessionId: string},
        TContext
      > => {

      const mutationOptions = getPostV1TmuxSessionsSessionIdReleaseMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Kills a tmux session
 * @summary Kill tmux session
 */
export const deleteV1TmuxSessionsSessionName = (
    sessionName: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteV1TmuxSessionsSessionName200>> => {
    
    
    return axios.default.delete(
      `/v1/tmux/sessions/${sessionName}`,options
    );
  }



export const getDeleteV1TmuxSessionsSessionNameMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1TmuxSessionsSessionName>>, TError,{sessionName: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1TmuxSessionsSessionName>>, TError,{sessionName: string}, TContext> => {

const mutationKey = ['deleteV1TmuxSessionsSessionName'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1TmuxSessionsSessionName>>, {sessionName: string}> = (props) => {
          const {sessionName} = props ?? {};

          return  deleteV1TmuxSessionsSessionName(sessionName,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1TmuxSessionsSessionNameMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1TmuxSessionsSessionName>>>
    
    export type DeleteV1TmuxSessionsSessionNameMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Kill tmux session
 */
export const useDeleteV1TmuxSessionsSessionName = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1TmuxSessionsSessionName>>, TError,{sessionName: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1TmuxSessionsSessionName>>,
        TError,
        {sessionName: string},
        TContext
      > => {

      const mutationOptions = getDeleteV1TmuxSessionsSessionNameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a new tmux session
 * @summary Create tmux session
 */
export const postV1TmuxSessionsCreate = (
    postV1TmuxSessionsCreateBody: PostV1TmuxSessionsCreateBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostV1TmuxSessionsCreate200>> => {
    
    
    return axios.default.post(
      `/v1/tmux/sessions/create`,
      postV1TmuxSessionsCreateBody,options
    );
  }



export const getPostV1TmuxSessionsCreateMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxSessionsCreate>>, TError,{data: PostV1TmuxSessionsCreateBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxSessionsCreate>>, TError,{data: PostV1TmuxSessionsCreateBody}, TContext> => {

const mutationKey = ['postV1TmuxSessionsCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1TmuxSessionsCreate>>, {data: PostV1TmuxSessionsCreateBody}> = (props) => {
          const {data} = props ?? {};

          return  postV1TmuxSessionsCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1TmuxSessionsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postV1TmuxSessionsCreate>>>
    export type PostV1TmuxSessionsCreateMutationBody = PostV1TmuxSessionsCreateBody
    export type PostV1TmuxSessionsCreateMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Create tmux session
 */
export const usePostV1TmuxSessionsCreate = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TmuxSessionsCreate>>, TError,{data: PostV1TmuxSessionsCreateBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1TmuxSessionsCreate>>,
        TError,
        {data: PostV1TmuxSessionsCreateBody},
        TContext
      > => {

      const mutationOptions = getPostV1TmuxSessionsCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get a list of windows in a tmux session
 * @summary List tmux windows
 */
export const getV1TmuxWindows = (
    params?: GetV1TmuxWindowsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesWindowInfo[]>> => {
    
    
    return axios.default.get(
      `/v1/tmux/windows`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetV1TmuxWindowsQueryKey = (params?: GetV1TmuxWindowsParams,) => {
    return [
    `/v1/tmux/windows`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetV1TmuxWindowsQueryOptions = <TData = Awaited<ReturnType<typeof getV1TmuxWindows>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(params?: GetV1TmuxWindowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxWindows>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1TmuxWindowsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1TmuxWindows>>> = ({ signal }) => getV1TmuxWindows(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxWindows>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1TmuxWindowsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1TmuxWindows>>>
export type GetV1TmuxWindowsQueryError = AxiosError<TmuxClientInternalTypesAPIError>


export function useGetV1TmuxWindows<TData = Awaited<ReturnType<typeof getV1TmuxWindows>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 params: undefined |  GetV1TmuxWindowsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxWindows>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1TmuxWindows>>,
          TError,
          Awaited<ReturnType<typeof getV1TmuxWindows>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1TmuxWindows<TData = Awaited<ReturnType<typeof getV1TmuxWindows>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 params?: GetV1TmuxWindowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxWindows>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1TmuxWindows>>,
          TError,
          Awaited<ReturnType<typeof getV1TmuxWindows>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1TmuxWindows<TData = Awaited<ReturnType<typeof getV1TmuxWindows>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 params?: GetV1TmuxWindowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxWindows>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List tmux windows
 */

export function useGetV1TmuxWindows<TData = Awaited<ReturnType<typeof getV1TmuxWindows>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 params?: GetV1TmuxWindowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1TmuxWindows>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1TmuxWindowsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




