// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/ansible/jobs": {
            "post": {
                "description": "Creates a new Ansible playbook execution job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ansible"
                ],
                "summary": "Create Ansible job",
                "parameters": [
                    {
                        "description": "Job creation parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ansible.JobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ansible.JobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_error.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/ansible/jobs/{job_id}": {
            "get": {
                "description": "Gets the status of an Ansible job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ansible"
                ],
                "summary": "Get Ansible job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ansible.Job"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_error.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/ansible/jobs/{job_id}/stream": {
            "get": {
                "description": "Connects via WebSocket to run an Ansible job and stream output",
                "tags": [
                    "Ansible"
                ],
                "summary": "Stream Ansible job output",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/health": {
            "get": {
                "description": "Returns service health status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/sandbox/create": {
            "post": {
                "description": "Creates a new virtual machine sandbox by cloning from an existing VM",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sandbox"
                ],
                "summary": "Create a new sandbox",
                "parameters": [
                    {
                        "description": "Sandbox creation parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.createSandboxRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.createSandboxResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sandbox/{id}": {
            "delete": {
                "description": "Destroys the sandbox and cleans up resources",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sandbox"
                ],
                "summary": "Destroy sandbox",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sandbox/{id}/diff": {
            "post": {
                "description": "Computes differences between two snapshots",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sandbox"
                ],
                "summary": "Diff snapshots",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Diff parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.diffRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.diffResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sandbox/{id}/generate/{tool}": {
            "post": {
                "description": "Generates Ansible or Puppet configuration from sandbox changes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sandbox"
                ],
                "summary": "Generate configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tool type (ansible or puppet)",
                        "name": "tool",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.generateResponse"
                        }
                    }
                }
            }
        },
        "/v1/sandbox/{id}/publish": {
            "post": {
                "description": "Publishes sandbox changes to GitOps repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sandbox"
                ],
                "summary": "Publish changes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Publish parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.publishRequest"
                        }
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.publishResponse"
                        }
                    }
                }
            }
        },
        "/v1/sandbox/{id}/run": {
            "post": {
                "description": "Executes a command inside the sandbox via SSH",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sandbox"
                ],
                "summary": "Run command in sandbox",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Command execution parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.runCommandRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.runCommandResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sandbox/{id}/snapshot": {
            "post": {
                "description": "Creates a snapshot of the sandbox",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sandbox"
                ],
                "summary": "Create snapshot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Snapshot parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.snapshotRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.snapshotResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sandbox/{id}/sshkey": {
            "post": {
                "description": "Injects a public SSH key for a user in the sandbox",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sandbox"
                ],
                "summary": "Inject SSH key into sandbox",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SSH key injection parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.injectSSHKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sandbox/{id}/start": {
            "post": {
                "description": "Starts the virtual machine sandbox",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sandbox"
                ],
                "summary": "Start sandbox",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Start parameters",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.startSandboxRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.startSandboxResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/vms": {
            "get": {
                "description": "Returns a list of all virtual machines from the libvirt instance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VMs"
                ],
                "summary": "List all VMs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.listVMsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/virsh-sandbox_internal_rest.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_ansible.Job": {
            "type": "object",
            "properties": {
                "check": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "playbook": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/internal_ansible.JobStatus"
                },
                "vm_name": {
                    "type": "string"
                }
            }
        },
        "internal_ansible.JobRequest": {
            "type": "object",
            "properties": {
                "check": {
                    "type": "boolean"
                },
                "playbook": {
                    "type": "string"
                },
                "vm_name": {
                    "type": "string"
                }
            }
        },
        "internal_ansible.JobResponse": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string"
                },
                "ws_url": {
                    "type": "string"
                }
            }
        },
        "internal_ansible.JobStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "finished",
                "failed"
            ],
            "x-enum-varnames": [
                "JobStatusPending",
                "JobStatusRunning",
                "JobStatusFinished",
                "JobStatusFailed"
            ]
        },
        "internal_rest.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_rest.createSandboxRequest": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "description": "required",
                    "type": "string"
                },
                "cpu": {
                    "description": "optional; default from service config if \u003c=0",
                    "type": "integer"
                },
                "memory_mb": {
                    "description": "optional; default from service config if \u003c=0",
                    "type": "integer"
                },
                "source_vm_name": {
                    "description": "required; name of existing VM in libvirt to clone from",
                    "type": "string"
                },
                "vm_name": {
                    "description": "optional; generated if empty",
                    "type": "string"
                }
            }
        },
        "internal_rest.createSandboxResponse": {
            "type": "object",
            "properties": {
                "sandbox": {
                    "$ref": "#/definitions/virsh-sandbox_internal_store.Sandbox"
                }
            }
        },
        "internal_rest.diffRequest": {
            "type": "object",
            "properties": {
                "from_snapshot": {
                    "description": "required",
                    "type": "string"
                },
                "to_snapshot": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "internal_rest.diffResponse": {
            "type": "object",
            "properties": {
                "diff": {
                    "$ref": "#/definitions/virsh-sandbox_internal_store.Diff"
                }
            }
        },
        "internal_rest.generateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "internal_rest.injectSSHKeyRequest": {
            "type": "object",
            "properties": {
                "public_key": {
                    "description": "required",
                    "type": "string"
                },
                "username": {
                    "description": "required (explicit); typical: \"ubuntu\" or \"centos\"",
                    "type": "string"
                }
            }
        },
        "internal_rest.listVMsResponse": {
            "type": "object",
            "properties": {
                "vms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_rest.vmInfo"
                    }
                }
            }
        },
        "internal_rest.publishRequest": {
            "type": "object",
            "properties": {
                "job_id": {
                    "description": "required",
                    "type": "string"
                },
                "message": {
                    "description": "optional commit/PR message",
                    "type": "string"
                },
                "reviewers": {
                    "description": "optional",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_rest.publishResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "internal_rest.runCommandRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "description": "required",
                    "type": "string"
                },
                "env": {
                    "description": "optional",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "private_key_path": {
                    "description": "required; path on API host",
                    "type": "string"
                },
                "timeout_sec": {
                    "description": "optional; default from service config",
                    "type": "integer"
                },
                "username": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "internal_rest.runCommandResponse": {
            "type": "object",
            "properties": {
                "command": {
                    "$ref": "#/definitions/virsh-sandbox_internal_store.Command"
                }
            }
        },
        "internal_rest.snapshotRequest": {
            "type": "object",
            "properties": {
                "external": {
                    "description": "optional; default false (internal snapshot)",
                    "type": "boolean"
                },
                "name": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "internal_rest.snapshotResponse": {
            "type": "object",
            "properties": {
                "snapshot": {
                    "$ref": "#/definitions/virsh-sandbox_internal_store.Snapshot"
                }
            }
        },
        "internal_rest.startSandboxRequest": {
            "type": "object",
            "properties": {
                "wait_for_ip": {
                    "description": "optional; default false",
                    "type": "boolean"
                }
            }
        },
        "internal_rest.startSandboxResponse": {
            "type": "object",
            "properties": {
                "ip_address": {
                    "type": "string"
                }
            }
        },
        "internal_rest.vmInfo": {
            "type": "object",
            "properties": {
                "disk_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "persistent": {
                    "type": "boolean"
                },
                "state": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "format": "int64",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        },
        "virsh-sandbox_internal_ansible.Job": {
            "type": "object",
            "properties": {
                "check": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "playbook": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/virsh-sandbox_internal_ansible.JobStatus"
                },
                "vm_name": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_ansible.JobRequest": {
            "type": "object",
            "properties": {
                "check": {
                    "type": "boolean"
                },
                "playbook": {
                    "type": "string"
                },
                "vm_name": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_ansible.JobResponse": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string"
                },
                "ws_url": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_ansible.JobStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "finished",
                "failed"
            ],
            "x-enum-varnames": [
                "JobStatusPending",
                "JobStatusRunning",
                "JobStatusFinished",
                "JobStatusFailed"
            ]
        },
        "virsh-sandbox_internal_error.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_rest.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_rest.createSandboxRequest": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "description": "required",
                    "type": "string"
                },
                "cpu": {
                    "description": "optional; default from service config if \u003c=0",
                    "type": "integer"
                },
                "memory_mb": {
                    "description": "optional; default from service config if \u003c=0",
                    "type": "integer"
                },
                "source_vm_name": {
                    "description": "required; name of existing VM in libvirt to clone from",
                    "type": "string"
                },
                "vm_name": {
                    "description": "optional; generated if empty",
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_rest.createSandboxResponse": {
            "type": "object",
            "properties": {
                "sandbox": {
                    "$ref": "#/definitions/virsh-sandbox_internal_store.Sandbox"
                }
            }
        },
        "virsh-sandbox_internal_rest.diffRequest": {
            "type": "object",
            "properties": {
                "from_snapshot": {
                    "description": "required",
                    "type": "string"
                },
                "to_snapshot": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_rest.diffResponse": {
            "type": "object",
            "properties": {
                "diff": {
                    "$ref": "#/definitions/virsh-sandbox_internal_store.Diff"
                }
            }
        },
        "virsh-sandbox_internal_rest.generateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_rest.injectSSHKeyRequest": {
            "type": "object",
            "properties": {
                "public_key": {
                    "description": "required",
                    "type": "string"
                },
                "username": {
                    "description": "required (explicit); typical: \"ubuntu\" or \"centos\"",
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_rest.listVMsResponse": {
            "type": "object",
            "properties": {
                "vms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/virsh-sandbox_internal_rest.vmInfo"
                    }
                }
            }
        },
        "virsh-sandbox_internal_rest.publishRequest": {
            "type": "object",
            "properties": {
                "job_id": {
                    "description": "required",
                    "type": "string"
                },
                "message": {
                    "description": "optional commit/PR message",
                    "type": "string"
                },
                "reviewers": {
                    "description": "optional",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "virsh-sandbox_internal_rest.publishResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_rest.runCommandRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "description": "required",
                    "type": "string"
                },
                "env": {
                    "description": "optional",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "private_key_path": {
                    "description": "required; path on API host",
                    "type": "string"
                },
                "timeout_sec": {
                    "description": "optional; default from service config",
                    "type": "integer"
                },
                "username": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_rest.runCommandResponse": {
            "type": "object",
            "properties": {
                "command": {
                    "$ref": "#/definitions/virsh-sandbox_internal_store.Command"
                }
            }
        },
        "virsh-sandbox_internal_rest.snapshotRequest": {
            "type": "object",
            "properties": {
                "external": {
                    "description": "optional; default false (internal snapshot)",
                    "type": "boolean"
                },
                "name": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_rest.snapshotResponse": {
            "type": "object",
            "properties": {
                "snapshot": {
                    "$ref": "#/definitions/virsh-sandbox_internal_store.Snapshot"
                }
            }
        },
        "virsh-sandbox_internal_rest.startSandboxRequest": {
            "type": "object",
            "properties": {
                "wait_for_ip": {
                    "description": "optional; default false",
                    "type": "boolean"
                }
            }
        },
        "virsh-sandbox_internal_rest.startSandboxResponse": {
            "type": "object",
            "properties": {
                "ip_address": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_rest.vmInfo": {
            "type": "object",
            "properties": {
                "disk_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "persistent": {
                    "type": "boolean"
                },
                "state": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_store.ChangeDiff": {
            "type": "object",
            "properties": {
                "commands_run": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/virsh-sandbox_internal_store.CommandSummary"
                    }
                },
                "files_added": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "files_modified": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "files_removed": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "packages_added": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/virsh-sandbox_internal_store.PackageInfo"
                    }
                },
                "packages_removed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/virsh-sandbox_internal_store.PackageInfo"
                    }
                },
                "services_changed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/virsh-sandbox_internal_store.ServiceChange"
                    }
                }
            }
        },
        "virsh-sandbox_internal_store.Command": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "ended_at": {
                    "type": "string"
                },
                "env_json": {
                    "description": "JSON-encoded env map",
                    "type": "string"
                },
                "exit_code": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/virsh-sandbox_internal_store.CommandExecRecord"
                },
                "sandbox_id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "stderr": {
                    "type": "string"
                },
                "stdout": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_store.CommandExecRecord": {
            "type": "object",
            "properties": {
                "redacted": {
                    "description": "placeholders for secrets redaction",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "timeout": {
                    "$ref": "#/definitions/time.Duration"
                },
                "user": {
                    "type": "string"
                },
                "work_dir": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_store.CommandSummary": {
            "type": "object",
            "properties": {
                "at": {
                    "type": "string"
                },
                "cmd": {
                    "type": "string"
                },
                "exit_code": {
                    "type": "integer"
                }
            }
        },
        "virsh-sandbox_internal_store.Diff": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "diff_json": {
                    "description": "JSON-encoded change diff",
                    "allOf": [
                        {
                            "$ref": "#/definitions/virsh-sandbox_internal_store.ChangeDiff"
                        }
                    ]
                },
                "from_snapshot": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "sandbox_id": {
                    "type": "string"
                },
                "to_snapshot": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_store.PackageInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_store.Sandbox": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "description": "requesting agent identity",
                    "type": "string"
                },
                "base_image": {
                    "description": "base qcow2 filename",
                    "type": "string"
                },
                "created_at": {
                    "description": "Metadata",
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "description": "e.g., \"SBX-0001\"",
                    "type": "string"
                },
                "ip_address": {
                    "description": "discovered IP (if any)",
                    "type": "string"
                },
                "job_id": {
                    "description": "correlation id for the end-to-end change set",
                    "type": "string"
                },
                "network": {
                    "description": "libvirt network name",
                    "type": "string"
                },
                "sandbox_name": {
                    "description": "libvirt domain name",
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/virsh-sandbox_internal_store.SandboxState"
                },
                "ttl_seconds": {
                    "description": "optional TTL for auto GC",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_store.SandboxState": {
            "type": "string",
            "enum": [
                "CREATED",
                "STARTING",
                "RUNNING",
                "STOPPED",
                "DESTROYED",
                "ERROR"
            ],
            "x-enum-varnames": [
                "SandboxStateCreated",
                "SandboxStateStarting",
                "SandboxStateRunning",
                "SandboxStateStopped",
                "SandboxStateDestroyed",
                "SandboxStateError"
            ]
        },
        "virsh-sandbox_internal_store.ServiceChange": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "state": {
                    "description": "started|stopped|restarted|reloaded",
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_store.Snapshot": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "$ref": "#/definitions/virsh-sandbox_internal_store.SnapshotKind"
                },
                "meta_json": {
                    "description": "optional JSON metadata",
                    "type": "string"
                },
                "name": {
                    "description": "logical name (unique per sandbox)",
                    "type": "string"
                },
                "ref": {
                    "description": "Ref is a backend-specific reference: for internal snapshots this could be a UUID or name,\nfor external snapshots it could be a file path to the overlay qcow2.",
                    "type": "string"
                },
                "sandbox_id": {
                    "type": "string"
                }
            }
        },
        "virsh-sandbox_internal_store.SnapshotKind": {
            "type": "string",
            "enum": [
                "INTERNAL",
                "EXTERNAL"
            ],
            "x-enum-varnames": [
                "SnapshotKindInternal",
                "SnapshotKindExternal"
            ]
        }
    },
    "tags": [
        {
            "description": "Sandbox lifecycle management - create, start, run commands, snapshot, and destroy sandboxes",
            "name": "Sandbox"
        },
        {
            "description": "Virtual machine listing and information",
            "name": "VMs"
        },
        {
            "description": "Ansible playbook job management",
            "name": "Ansible"
        },
        {
            "description": "Health check endpoints",
            "name": "Health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1-beta",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "virsh-sandbox API",
	Description:      "API for managing virtual machine sandboxes using libvirt",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
