/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */

export interface TmuxClientInternalTypesEditFileResponse {
  /** For audit trail */
  content_after?: string;
  /** For audit trail */
  content_before?: string;
  /** Unified diff format */
  diff?: string;
  edited?: boolean;
  path?: string;
  replacements?: number;
}
