/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */

export interface TmuxClientInternalTypesAuditQuery {
  action?: string;
  limit?: number;
  request_id?: string;
  since?: string;
  tool?: string;
  until?: string;
}
