/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */

export interface TmuxClientInternalTypesReadFileRequest {
  /** 1-indexed, 0 = start */
  from_line?: number;
  /** 0 = no limit */
  max_lines?: number;
  path?: string;
  /** 1-indexed, 0 = end */
  to_line?: number;
}
