/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */

export type TmuxClientInternalTypesPlanStatus = typeof TmuxClientInternalTypesPlanStatus[keyof typeof TmuxClientInternalTypesPlanStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TmuxClientInternalTypesPlanStatus = {
  PlanStatusPending: 'pending',
  PlanStatusInProgress: 'in_progress',
  PlanStatusCompleted: 'completed',
  PlanStatusFailed: 'failed',
  PlanStatusAborted: 'aborted',
} as const;
