/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */

export interface TmuxClientInternalTypesPaneInfo {
  active?: boolean;
  current_path?: string;
  pane_height?: number;
  pane_id?: string;
  pane_index?: number;
  pane_pid?: number;
  pane_title?: string;
  pane_width?: number;
  session_name?: string;
  window_index?: number;
  window_name?: string;
}
