/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */

export interface TmuxClientInternalTypesCreatePaneRequest {
  command?: string;
  /** false = vertical split */
  horizontal?: boolean;
  /** true = create new window instead of split */
  new_window?: boolean;
  session_name?: string;
  window_name?: string;
}
