/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */

export interface TmuxClientInternalTypesAskHumanRequest {
  /** Category: "destructive", "sensitive", "irreversible" */
  action_type?: string;
  /** Suggested alternative actions */
  alternatives?: string[];
  /** Additional context */
  context?: string;
  /** Human-readable description */
  prompt?: string;
  /** Auto-reject after timeout, 0 = no timeout */
  timeout_secs?: number;
  /** "low", "medium", "high" */
  urgency?: string;
}
