/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */

export interface TmuxClientInternalTypesEditFileRequest {
  /** Replace all occurrences (default: first only) */
  all?: boolean;
  /** Replacement text */
  new_text?: string;
  /** Text to find and replace */
  old_text?: string;
  path?: string;
}
