# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TimeDuration(int, Enum):
    """
    TimeDuration
    """

    """
    allowed enum values
    """
    minDuration = -9223372036854775808
    maxDuration = 9223372036854775807
    Nanosecond = 1
    Microsecond = 1000
    Millisecond = 1000000
    Second = 1000000000
    Minute = 60000000000
    Hour = 3600000000000

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TimeDuration from a JSON string"""
        return cls(json.loads(json_str))


