# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.virsh_sandbox_internal_rest_ca_public_key_response import \
    VirshSandboxInternalRestCaPublicKeyResponse


class TestVirshSandboxInternalRestCaPublicKeyResponse(unittest.TestCase):
    """VirshSandboxInternalRestCaPublicKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> VirshSandboxInternalRestCaPublicKeyResponse:
        """Test VirshSandboxInternalRestCaPublicKeyResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `VirshSandboxInternalRestCaPublicKeyResponse`
        """
        model = VirshSandboxInternalRestCaPublicKeyResponse()
        if include_optional:
            return VirshSandboxInternalRestCaPublicKeyResponse(
                public_key = '',
                usage = ''
            )
        else:
            return VirshSandboxInternalRestCaPublicKeyResponse(
        )
        """

    def testVirshSandboxInternalRestCaPublicKeyResponse(self):
        """Test VirshSandboxInternalRestCaPublicKeyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
