# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.api.access_api import AccessApi


class TestAccessApi(unittest.TestCase):
    """AccessApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccessApi()

    def tearDown(self) -> None:
        pass

    def test_v1_access_ca_pubkey_get(self) -> None:
        """Test case for v1_access_ca_pubkey_get

        Get the SSH CA public key
        """
        pass

    def test_v1_access_certificate_cert_id_delete(self) -> None:
        """Test case for v1_access_certificate_cert_id_delete

        Revoke a certificate
        """
        pass

    def test_v1_access_certificate_cert_id_get(self) -> None:
        """Test case for v1_access_certificate_cert_id_get

        Get certificate details
        """
        pass

    def test_v1_access_certificates_get(self) -> None:
        """Test case for v1_access_certificates_get

        List certificates
        """
        pass

    def test_v1_access_request_post(self) -> None:
        """Test case for v1_access_request_post

        Request SSH access to a sandbox
        """
        pass

    def test_v1_access_session_end_post(self) -> None:
        """Test case for v1_access_session_end_post

        Record session end
        """
        pass

    def test_v1_access_session_start_post(self) -> None:
        """Test case for v1_access_session_start_post

        Record session start
        """
        pass

    def test_v1_access_sessions_get(self) -> None:
        """Test case for v1_access_sessions_get

        List sessions
        """
        pass


if __name__ == "__main__":
    unittest.main()
