# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.internal_rest_session_response import \
    InternalRestSessionResponse


class TestInternalRestSessionResponse(unittest.TestCase):
    """InternalRestSessionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalRestSessionResponse:
        """Test InternalRestSessionResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `InternalRestSessionResponse`
        """
        model = InternalRestSessionResponse()
        if include_optional:
            return InternalRestSessionResponse(
                certificate_id = '',
                duration_seconds = 56,
                ended_at = '',
                id = '',
                sandbox_id = '',
                source_ip = '',
                started_at = '',
                status = '',
                user_id = '',
                vm_id = '',
                vm_ip_address = ''
            )
        else:
            return InternalRestSessionResponse(
        )
        """

    def testInternalRestSessionResponse(self):
        """Test InternalRestSessionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
