# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.virsh_sandbox_internal_rest_list_sessions_response import \
    VirshSandboxInternalRestListSessionsResponse


class TestVirshSandboxInternalRestListSessionsResponse(unittest.TestCase):
    """VirshSandboxInternalRestListSessionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> VirshSandboxInternalRestListSessionsResponse:
        """Test VirshSandboxInternalRestListSessionsResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `VirshSandboxInternalRestListSessionsResponse`
        """
        model = VirshSandboxInternalRestListSessionsResponse()
        if include_optional:
            return VirshSandboxInternalRestListSessionsResponse(
                sessions = [
                    {"certificate_id":"certificate_id","duration_seconds":0,"vm_id":"vm_id","user_id":"user_id","sandbox_id":"sandbox_id","started_at":"started_at","vm_ip_address":"vm_ip_address","id":"id","ended_at":"ended_at","source_ip":"source_ip","status":"status"}
                    ],
                total = 56
            )
        else:
            return VirshSandboxInternalRestListSessionsResponse(
        )
        """

    def testVirshSandboxInternalRestListSessionsResponse(self):
        """Test VirshSandboxInternalRestListSessionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
