# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.virsh_sandbox_internal_rest_session_end_request import \
    VirshSandboxInternalRestSessionEndRequest


class TestVirshSandboxInternalRestSessionEndRequest(unittest.TestCase):
    """VirshSandboxInternalRestSessionEndRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> VirshSandboxInternalRestSessionEndRequest:
        """Test VirshSandboxInternalRestSessionEndRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `VirshSandboxInternalRestSessionEndRequest`
        """
        model = VirshSandboxInternalRestSessionEndRequest()
        if include_optional:
            return VirshSandboxInternalRestSessionEndRequest(
                reason = '',
                session_id = ''
            )
        else:
            return VirshSandboxInternalRestSessionEndRequest(
        )
        """

    def testVirshSandboxInternalRestSessionEndRequest(self):
        """Test VirshSandboxInternalRestSessionEndRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
