/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeleteV1HumanPendingRequestID200,
  PostV1HumanAskAsync200,
  TmuxClientInternalTypesAPIError,
  TmuxClientInternalTypesApproveRequest,
  TmuxClientInternalTypesAskHumanRequest,
  TmuxClientInternalTypesAskHumanResponse,
  TmuxClientInternalTypesListApprovalsResponse,
  TmuxClientInternalTypesPendingApproval
} from '.././model';





/**
 * Requests approval from a human for an action
 * @summary Request human approval
 */
export const postV1HumanAsk = (
    tmuxClientInternalTypesAskHumanRequest: TmuxClientInternalTypesAskHumanRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesAskHumanResponse>> => {
    
    
    return axios.default.post(
      `/v1/human/ask`,
      tmuxClientInternalTypesAskHumanRequest,options
    );
  }



export const getPostV1HumanAskMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1HumanAsk>>, TError,{data: TmuxClientInternalTypesAskHumanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1HumanAsk>>, TError,{data: TmuxClientInternalTypesAskHumanRequest}, TContext> => {

const mutationKey = ['postV1HumanAsk'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1HumanAsk>>, {data: TmuxClientInternalTypesAskHumanRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1HumanAsk(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1HumanAskMutationResult = NonNullable<Awaited<ReturnType<typeof postV1HumanAsk>>>
    export type PostV1HumanAskMutationBody = TmuxClientInternalTypesAskHumanRequest
    export type PostV1HumanAskMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Request human approval
 */
export const usePostV1HumanAsk = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1HumanAsk>>, TError,{data: TmuxClientInternalTypesAskHumanRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1HumanAsk>>,
        TError,
        {data: TmuxClientInternalTypesAskHumanRequest},
        TContext
      > => {

      const mutationOptions = getPostV1HumanAskMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Requests approval from a human asynchronously
 * @summary Request human approval asynchronously
 */
export const postV1HumanAskAsync = (
    tmuxClientInternalTypesAskHumanRequest: TmuxClientInternalTypesAskHumanRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostV1HumanAskAsync200>> => {
    
    
    return axios.default.post(
      `/v1/human/ask-async`,
      tmuxClientInternalTypesAskHumanRequest,options
    );
  }



export const getPostV1HumanAskAsyncMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1HumanAskAsync>>, TError,{data: TmuxClientInternalTypesAskHumanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1HumanAskAsync>>, TError,{data: TmuxClientInternalTypesAskHumanRequest}, TContext> => {

const mutationKey = ['postV1HumanAskAsync'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1HumanAskAsync>>, {data: TmuxClientInternalTypesAskHumanRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1HumanAskAsync(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1HumanAskAsyncMutationResult = NonNullable<Awaited<ReturnType<typeof postV1HumanAskAsync>>>
    export type PostV1HumanAskAsyncMutationBody = TmuxClientInternalTypesAskHumanRequest
    export type PostV1HumanAskAsyncMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Request human approval asynchronously
 */
export const usePostV1HumanAskAsync = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1HumanAskAsync>>, TError,{data: TmuxClientInternalTypesAskHumanRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1HumanAskAsync>>,
        TError,
        {data: TmuxClientInternalTypesAskHumanRequest},
        TContext
      > => {

      const mutationOptions = getPostV1HumanAskAsyncMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Lists all pending human approval requests
 * @summary List pending approvals
 */
export const getV1HumanPending = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesListApprovalsResponse>> => {
    
    
    return axios.default.get(
      `/v1/human/pending`,options
    );
  }




export const getGetV1HumanPendingQueryKey = () => {
    return [
    `/v1/human/pending`
    ] as const;
    }

    
export const getGetV1HumanPendingQueryOptions = <TData = Awaited<ReturnType<typeof getV1HumanPending>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1HumanPending>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1HumanPendingQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1HumanPending>>> = ({ signal }) => getV1HumanPending({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1HumanPending>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1HumanPendingQueryResult = NonNullable<Awaited<ReturnType<typeof getV1HumanPending>>>
export type GetV1HumanPendingQueryError = AxiosError<unknown>


export function useGetV1HumanPending<TData = Awaited<ReturnType<typeof getV1HumanPending>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1HumanPending>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1HumanPending>>,
          TError,
          Awaited<ReturnType<typeof getV1HumanPending>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1HumanPending<TData = Awaited<ReturnType<typeof getV1HumanPending>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1HumanPending>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1HumanPending>>,
          TError,
          Awaited<ReturnType<typeof getV1HumanPending>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1HumanPending<TData = Awaited<ReturnType<typeof getV1HumanPending>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1HumanPending>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List pending approvals
 */

export function useGetV1HumanPending<TData = Awaited<ReturnType<typeof getV1HumanPending>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1HumanPending>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1HumanPendingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Cancels a pending approval request
 * @summary Cancel approval
 */
export const deleteV1HumanPendingRequestID = (
    requestID: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteV1HumanPendingRequestID200>> => {
    
    
    return axios.default.delete(
      `/v1/human/pending/${requestID}`,options
    );
  }



export const getDeleteV1HumanPendingRequestIDMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1HumanPendingRequestID>>, TError,{requestID: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1HumanPendingRequestID>>, TError,{requestID: string}, TContext> => {

const mutationKey = ['deleteV1HumanPendingRequestID'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1HumanPendingRequestID>>, {requestID: string}> = (props) => {
          const {requestID} = props ?? {};

          return  deleteV1HumanPendingRequestID(requestID,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1HumanPendingRequestIDMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1HumanPendingRequestID>>>
    
    export type DeleteV1HumanPendingRequestIDMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Cancel approval
 */
export const useDeleteV1HumanPendingRequestID = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1HumanPendingRequestID>>, TError,{requestID: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1HumanPendingRequestID>>,
        TError,
        {requestID: string},
        TContext
      > => {

      const mutationOptions = getDeleteV1HumanPendingRequestIDMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieves a specific pending approval request
 * @summary Get pending approval
 */
export const getV1HumanPendingRequestID = (
    requestID: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesPendingApproval>> => {
    
    
    return axios.default.get(
      `/v1/human/pending/${requestID}`,options
    );
  }




export const getGetV1HumanPendingRequestIDQueryKey = (requestID?: string,) => {
    return [
    `/v1/human/pending/${requestID}`
    ] as const;
    }

    
export const getGetV1HumanPendingRequestIDQueryOptions = <TData = Awaited<ReturnType<typeof getV1HumanPendingRequestID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(requestID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1HumanPendingRequestID>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1HumanPendingRequestIDQueryKey(requestID);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1HumanPendingRequestID>>> = ({ signal }) => getV1HumanPendingRequestID(requestID, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(requestID), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1HumanPendingRequestID>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1HumanPendingRequestIDQueryResult = NonNullable<Awaited<ReturnType<typeof getV1HumanPendingRequestID>>>
export type GetV1HumanPendingRequestIDQueryError = AxiosError<TmuxClientInternalTypesAPIError>


export function useGetV1HumanPendingRequestID<TData = Awaited<ReturnType<typeof getV1HumanPendingRequestID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 requestID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1HumanPendingRequestID>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1HumanPendingRequestID>>,
          TError,
          Awaited<ReturnType<typeof getV1HumanPendingRequestID>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1HumanPendingRequestID<TData = Awaited<ReturnType<typeof getV1HumanPendingRequestID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 requestID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1HumanPendingRequestID>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1HumanPendingRequestID>>,
          TError,
          Awaited<ReturnType<typeof getV1HumanPendingRequestID>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1HumanPendingRequestID<TData = Awaited<ReturnType<typeof getV1HumanPendingRequestID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 requestID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1HumanPendingRequestID>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get pending approval
 */

export function useGetV1HumanPendingRequestID<TData = Awaited<ReturnType<typeof getV1HumanPendingRequestID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 requestID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1HumanPendingRequestID>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1HumanPendingRequestIDQueryOptions(requestID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Responds to a pending approval request
 * @summary Respond to approval
 */
export const postV1HumanRespond = (
    tmuxClientInternalTypesApproveRequest: TmuxClientInternalTypesApproveRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesAskHumanResponse>> => {
    
    
    return axios.default.post(
      `/v1/human/respond`,
      tmuxClientInternalTypesApproveRequest,options
    );
  }



export const getPostV1HumanRespondMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1HumanRespond>>, TError,{data: TmuxClientInternalTypesApproveRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1HumanRespond>>, TError,{data: TmuxClientInternalTypesApproveRequest}, TContext> => {

const mutationKey = ['postV1HumanRespond'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1HumanRespond>>, {data: TmuxClientInternalTypesApproveRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1HumanRespond(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1HumanRespondMutationResult = NonNullable<Awaited<ReturnType<typeof postV1HumanRespond>>>
    export type PostV1HumanRespondMutationBody = TmuxClientInternalTypesApproveRequest
    export type PostV1HumanRespondMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Respond to approval
 */
export const usePostV1HumanRespond = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1HumanRespond>>, TError,{data: TmuxClientInternalTypesApproveRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1HumanRespond>>,
        TError,
        {data: TmuxClientInternalTypesApproveRequest},
        TContext
      > => {

      const mutationOptions = getPostV1HumanRespondMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    