/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  InternalAnsibleJobStatus
} from '.././model';
import type {
  InternalAnsibleJob,
  InternalAnsibleJobResponse
} from '.././model';


export const getPostV1AnsibleJobsResponseMock = (overrideResponse: Partial< InternalAnsibleJobResponse > = {}): InternalAnsibleJobResponse => ({job_id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ws_url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getGetV1AnsibleJobsJobIdResponseMock = (overrideResponse: Partial< InternalAnsibleJob > = {}): InternalAnsibleJob => ({check: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), playbook: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(Object.values(InternalAnsibleJobStatus)), undefined]), vm_name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})


export const getPostV1AnsibleJobsMockHandler = (overrideResponse?: InternalAnsibleJobResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<InternalAnsibleJobResponse> | InternalAnsibleJobResponse), options?: RequestHandlerOptions) => {
  return http.post('*/v1/ansible/jobs', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostV1AnsibleJobsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetV1AnsibleJobsJobIdMockHandler = (overrideResponse?: InternalAnsibleJob | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<InternalAnsibleJob> | InternalAnsibleJob), options?: RequestHandlerOptions) => {
  return http.get('*/v1/ansible/jobs/:jobId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetV1AnsibleJobsJobIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetV1AnsibleJobsJobIdStreamMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.get('*/v1/ansible/jobs/:jobId/stream', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getAnsibleMock = () => [
  getPostV1AnsibleJobsMockHandler(),
  getGetV1AnsibleJobsJobIdMockHandler(),
  getGetV1AnsibleJobsJobIdStreamMockHandler()
]
