/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  TmuxClientInternalTypesHealthStatus
} from '.././model';
import type {
  TmuxClientInternalTypesHealthResponse
} from '.././model';


export const getGetV1HealthResponseMock = (overrideResponse: Partial< TmuxClientInternalTypesHealthResponse > = {}): TmuxClientInternalTypesHealthResponse => ({components: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(Object.values(TmuxClientInternalTypesHealthStatus)), undefined])})), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(Object.values(TmuxClientInternalTypesHealthStatus)), undefined]), uptime: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), version: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})


export const getGetV1HealthMockHandler = (overrideResponse?: TmuxClientInternalTypesHealthResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TmuxClientInternalTypesHealthResponse> | TmuxClientInternalTypesHealthResponse), options?: RequestHandlerOptions) => {
  return http.get('*/v1/health', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetV1HealthResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getHealthMock = () => [
  getGetV1HealthMockHandler()
]
