/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  VirshSandboxInternalRestCreateSandboxRequest,
  VirshSandboxInternalRestCreateSandboxResponse,
  VirshSandboxInternalRestDiffRequest,
  VirshSandboxInternalRestDiffResponse,
  VirshSandboxInternalRestErrorResponse,
  VirshSandboxInternalRestGenerateResponse,
  VirshSandboxInternalRestInjectSSHKeyRequest,
  VirshSandboxInternalRestPublishRequest,
  VirshSandboxInternalRestPublishResponse,
  VirshSandboxInternalRestRunCommandRequest,
  VirshSandboxInternalRestRunCommandResponse,
  VirshSandboxInternalRestSnapshotRequest,
  VirshSandboxInternalRestSnapshotResponse,
  VirshSandboxInternalRestStartSandboxRequest,
  VirshSandboxInternalRestStartSandboxResponse
} from '.././model';





/**
 * Destroys the sandbox and cleans up resources
 * @summary Destroy sandbox
 */
export const deleteV1SandboxId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/v1/sandbox/${id}`,options
    );
  }



export const getDeleteV1SandboxIdMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1SandboxId>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1SandboxId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteV1SandboxId'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1SandboxId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteV1SandboxId(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1SandboxIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1SandboxId>>>
    
    export type DeleteV1SandboxIdMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Destroy sandbox
 */
export const useDeleteV1SandboxId = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1SandboxId>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1SandboxId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteV1SandboxIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Computes differences between two snapshots
 * @summary Diff snapshots
 */
export const postV1SandboxIdDiff = (
    id: string,
    virshSandboxInternalRestDiffRequest: VirshSandboxInternalRestDiffRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VirshSandboxInternalRestDiffResponse>> => {
    
    
    return axios.default.post(
      `/v1/sandbox/${id}/diff`,
      virshSandboxInternalRestDiffRequest,options
    );
  }



export const getPostV1SandboxIdDiffMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdDiff>>, TError,{id: string;data: VirshSandboxInternalRestDiffRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdDiff>>, TError,{id: string;data: VirshSandboxInternalRestDiffRequest}, TContext> => {

const mutationKey = ['postV1SandboxIdDiff'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1SandboxIdDiff>>, {id: string;data: VirshSandboxInternalRestDiffRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postV1SandboxIdDiff(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1SandboxIdDiffMutationResult = NonNullable<Awaited<ReturnType<typeof postV1SandboxIdDiff>>>
    export type PostV1SandboxIdDiffMutationBody = VirshSandboxInternalRestDiffRequest
    export type PostV1SandboxIdDiffMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Diff snapshots
 */
export const usePostV1SandboxIdDiff = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdDiff>>, TError,{id: string;data: VirshSandboxInternalRestDiffRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1SandboxIdDiff>>,
        TError,
        {id: string;data: VirshSandboxInternalRestDiffRequest},
        TContext
      > => {

      const mutationOptions = getPostV1SandboxIdDiffMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Generates Ansible or Puppet configuration from sandbox changes
 * @summary Generate configuration
 */
export const postV1SandboxIdGenerateTool = (
    id: string,
    tool: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/v1/sandbox/${id}/generate/${tool}`,undefined,options
    );
  }



export const getPostV1SandboxIdGenerateToolMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse | VirshSandboxInternalRestGenerateResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdGenerateTool>>, TError,{id: string;tool: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdGenerateTool>>, TError,{id: string;tool: string}, TContext> => {

const mutationKey = ['postV1SandboxIdGenerateTool'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1SandboxIdGenerateTool>>, {id: string;tool: string}> = (props) => {
          const {id,tool} = props ?? {};

          return  postV1SandboxIdGenerateTool(id,tool,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1SandboxIdGenerateToolMutationResult = NonNullable<Awaited<ReturnType<typeof postV1SandboxIdGenerateTool>>>
    
    export type PostV1SandboxIdGenerateToolMutationError = AxiosError<VirshSandboxInternalRestErrorResponse | VirshSandboxInternalRestGenerateResponse>

    /**
 * @summary Generate configuration
 */
export const usePostV1SandboxIdGenerateTool = <TError = AxiosError<VirshSandboxInternalRestErrorResponse | VirshSandboxInternalRestGenerateResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdGenerateTool>>, TError,{id: string;tool: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1SandboxIdGenerateTool>>,
        TError,
        {id: string;tool: string},
        TContext
      > => {

      const mutationOptions = getPostV1SandboxIdGenerateToolMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Publishes sandbox changes to GitOps repository
 * @summary Publish changes
 */
export const postV1SandboxIdPublish = (
    id: string,
    virshSandboxInternalRestPublishRequest: VirshSandboxInternalRestPublishRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/v1/sandbox/${id}/publish`,
      virshSandboxInternalRestPublishRequest,options
    );
  }



export const getPostV1SandboxIdPublishMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse | VirshSandboxInternalRestPublishResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdPublish>>, TError,{id: string;data: VirshSandboxInternalRestPublishRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdPublish>>, TError,{id: string;data: VirshSandboxInternalRestPublishRequest}, TContext> => {

const mutationKey = ['postV1SandboxIdPublish'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1SandboxIdPublish>>, {id: string;data: VirshSandboxInternalRestPublishRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postV1SandboxIdPublish(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1SandboxIdPublishMutationResult = NonNullable<Awaited<ReturnType<typeof postV1SandboxIdPublish>>>
    export type PostV1SandboxIdPublishMutationBody = VirshSandboxInternalRestPublishRequest
    export type PostV1SandboxIdPublishMutationError = AxiosError<VirshSandboxInternalRestErrorResponse | VirshSandboxInternalRestPublishResponse>

    /**
 * @summary Publish changes
 */
export const usePostV1SandboxIdPublish = <TError = AxiosError<VirshSandboxInternalRestErrorResponse | VirshSandboxInternalRestPublishResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdPublish>>, TError,{id: string;data: VirshSandboxInternalRestPublishRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1SandboxIdPublish>>,
        TError,
        {id: string;data: VirshSandboxInternalRestPublishRequest},
        TContext
      > => {

      const mutationOptions = getPostV1SandboxIdPublishMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Executes a command inside the sandbox via SSH
 * @summary Run command in sandbox
 */
export const postV1SandboxIdRun = (
    id: string,
    virshSandboxInternalRestRunCommandRequest: VirshSandboxInternalRestRunCommandRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VirshSandboxInternalRestRunCommandResponse>> => {
    
    
    return axios.default.post(
      `/v1/sandbox/${id}/run`,
      virshSandboxInternalRestRunCommandRequest,options
    );
  }



export const getPostV1SandboxIdRunMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdRun>>, TError,{id: string;data: VirshSandboxInternalRestRunCommandRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdRun>>, TError,{id: string;data: VirshSandboxInternalRestRunCommandRequest}, TContext> => {

const mutationKey = ['postV1SandboxIdRun'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1SandboxIdRun>>, {id: string;data: VirshSandboxInternalRestRunCommandRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postV1SandboxIdRun(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1SandboxIdRunMutationResult = NonNullable<Awaited<ReturnType<typeof postV1SandboxIdRun>>>
    export type PostV1SandboxIdRunMutationBody = VirshSandboxInternalRestRunCommandRequest
    export type PostV1SandboxIdRunMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Run command in sandbox
 */
export const usePostV1SandboxIdRun = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdRun>>, TError,{id: string;data: VirshSandboxInternalRestRunCommandRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1SandboxIdRun>>,
        TError,
        {id: string;data: VirshSandboxInternalRestRunCommandRequest},
        TContext
      > => {

      const mutationOptions = getPostV1SandboxIdRunMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a snapshot of the sandbox
 * @summary Create snapshot
 */
export const postV1SandboxIdSnapshot = (
    id: string,
    virshSandboxInternalRestSnapshotRequest: VirshSandboxInternalRestSnapshotRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VirshSandboxInternalRestSnapshotResponse>> => {
    
    
    return axios.default.post(
      `/v1/sandbox/${id}/snapshot`,
      virshSandboxInternalRestSnapshotRequest,options
    );
  }



export const getPostV1SandboxIdSnapshotMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdSnapshot>>, TError,{id: string;data: VirshSandboxInternalRestSnapshotRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdSnapshot>>, TError,{id: string;data: VirshSandboxInternalRestSnapshotRequest}, TContext> => {

const mutationKey = ['postV1SandboxIdSnapshot'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1SandboxIdSnapshot>>, {id: string;data: VirshSandboxInternalRestSnapshotRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postV1SandboxIdSnapshot(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1SandboxIdSnapshotMutationResult = NonNullable<Awaited<ReturnType<typeof postV1SandboxIdSnapshot>>>
    export type PostV1SandboxIdSnapshotMutationBody = VirshSandboxInternalRestSnapshotRequest
    export type PostV1SandboxIdSnapshotMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Create snapshot
 */
export const usePostV1SandboxIdSnapshot = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdSnapshot>>, TError,{id: string;data: VirshSandboxInternalRestSnapshotRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1SandboxIdSnapshot>>,
        TError,
        {id: string;data: VirshSandboxInternalRestSnapshotRequest},
        TContext
      > => {

      const mutationOptions = getPostV1SandboxIdSnapshotMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Injects a public SSH key for a user in the sandbox
 * @summary Inject SSH key into sandbox
 */
export const postV1SandboxIdSshkey = (
    id: string,
    virshSandboxInternalRestInjectSSHKeyRequest: VirshSandboxInternalRestInjectSSHKeyRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/v1/sandbox/${id}/sshkey`,
      virshSandboxInternalRestInjectSSHKeyRequest,options
    );
  }



export const getPostV1SandboxIdSshkeyMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdSshkey>>, TError,{id: string;data: VirshSandboxInternalRestInjectSSHKeyRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdSshkey>>, TError,{id: string;data: VirshSandboxInternalRestInjectSSHKeyRequest}, TContext> => {

const mutationKey = ['postV1SandboxIdSshkey'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1SandboxIdSshkey>>, {id: string;data: VirshSandboxInternalRestInjectSSHKeyRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postV1SandboxIdSshkey(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1SandboxIdSshkeyMutationResult = NonNullable<Awaited<ReturnType<typeof postV1SandboxIdSshkey>>>
    export type PostV1SandboxIdSshkeyMutationBody = VirshSandboxInternalRestInjectSSHKeyRequest
    export type PostV1SandboxIdSshkeyMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Inject SSH key into sandbox
 */
export const usePostV1SandboxIdSshkey = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdSshkey>>, TError,{id: string;data: VirshSandboxInternalRestInjectSSHKeyRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1SandboxIdSshkey>>,
        TError,
        {id: string;data: VirshSandboxInternalRestInjectSSHKeyRequest},
        TContext
      > => {

      const mutationOptions = getPostV1SandboxIdSshkeyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Starts the virtual machine sandbox
 * @summary Start sandbox
 */
export const postV1SandboxIdStart = (
    id: string,
    virshSandboxInternalRestStartSandboxRequest: VirshSandboxInternalRestStartSandboxRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VirshSandboxInternalRestStartSandboxResponse>> => {
    
    
    return axios.default.post(
      `/v1/sandbox/${id}/start`,
      virshSandboxInternalRestStartSandboxRequest,options
    );
  }



export const getPostV1SandboxIdStartMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdStart>>, TError,{id: string;data: VirshSandboxInternalRestStartSandboxRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdStart>>, TError,{id: string;data: VirshSandboxInternalRestStartSandboxRequest}, TContext> => {

const mutationKey = ['postV1SandboxIdStart'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1SandboxIdStart>>, {id: string;data: VirshSandboxInternalRestStartSandboxRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postV1SandboxIdStart(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1SandboxIdStartMutationResult = NonNullable<Awaited<ReturnType<typeof postV1SandboxIdStart>>>
    export type PostV1SandboxIdStartMutationBody = VirshSandboxInternalRestStartSandboxRequest
    export type PostV1SandboxIdStartMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Start sandbox
 */
export const usePostV1SandboxIdStart = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxIdStart>>, TError,{id: string;data: VirshSandboxInternalRestStartSandboxRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1SandboxIdStart>>,
        TError,
        {id: string;data: VirshSandboxInternalRestStartSandboxRequest},
        TContext
      > => {

      const mutationOptions = getPostV1SandboxIdStartMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a new virtual machine sandbox by cloning from an existing VM
 * @summary Create a new sandbox
 */
export const postV1SandboxCreate = (
    virshSandboxInternalRestCreateSandboxRequest: VirshSandboxInternalRestCreateSandboxRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VirshSandboxInternalRestCreateSandboxResponse>> => {
    
    
    return axios.default.post(
      `/v1/sandbox/create`,
      virshSandboxInternalRestCreateSandboxRequest,options
    );
  }



export const getPostV1SandboxCreateMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxCreate>>, TError,{data: VirshSandboxInternalRestCreateSandboxRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxCreate>>, TError,{data: VirshSandboxInternalRestCreateSandboxRequest}, TContext> => {

const mutationKey = ['postV1SandboxCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1SandboxCreate>>, {data: VirshSandboxInternalRestCreateSandboxRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1SandboxCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1SandboxCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postV1SandboxCreate>>>
    export type PostV1SandboxCreateMutationBody = VirshSandboxInternalRestCreateSandboxRequest
    export type PostV1SandboxCreateMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Create a new sandbox
 */
export const usePostV1SandboxCreate = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1SandboxCreate>>, TError,{data: VirshSandboxInternalRestCreateSandboxRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1SandboxCreate>>,
        TError,
        {data: VirshSandboxInternalRestCreateSandboxRequest},
        TContext
      > => {

      const mutationOptions = getPostV1SandboxCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    