# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ansible_api import AnsibleApi


class TestAnsibleApi(unittest.TestCase):
    """AnsibleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnsibleApi()

    def tearDown(self) -> None:
        pass

    def test_v1_ansible_jobs_job_id_get(self) -> None:
        """Test case for v1_ansible_jobs_job_id_get

        Get Ansible job
        """
        pass

    def test_v1_ansible_jobs_job_id_stream_get(self) -> None:
        """Test case for v1_ansible_jobs_job_id_stream_get

        Stream Ansible job output
        """
        pass

    def test_v1_ansible_jobs_post(self) -> None:
        """Test case for v1_ansible_jobs_post

        Create Ansible job
        """
        pass


if __name__ == '__main__':
    unittest.main()
