# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.vms_api import VMsApi


class TestVMsApi(unittest.TestCase):
    """VMsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VMsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_vms_get(self) -> None:
        """Test case for v1_vms_get

        List all VMs
        """
        pass


if __name__ == '__main__':
    unittest.main()
