# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.sandbox_api import SandboxApi


class TestSandboxApi(unittest.TestCase):
    """SandboxApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SandboxApi()

    def tearDown(self) -> None:
        pass

    def test_v1_sandbox_create_post(self) -> None:
        """Test case for v1_sandbox_create_post

        Create a new sandbox
        """
        pass

    def test_v1_sandbox_id_delete(self) -> None:
        """Test case for v1_sandbox_id_delete

        Destroy sandbox
        """
        pass

    def test_v1_sandbox_id_diff_post(self) -> None:
        """Test case for v1_sandbox_id_diff_post

        Diff snapshots
        """
        pass

    def test_v1_sandbox_id_generate_tool_post(self) -> None:
        """Test case for v1_sandbox_id_generate_tool_post

        Generate configuration
        """
        pass

    def test_v1_sandbox_id_publish_post(self) -> None:
        """Test case for v1_sandbox_id_publish_post

        Publish changes
        """
        pass

    def test_v1_sandbox_id_run_post(self) -> None:
        """Test case for v1_sandbox_id_run_post

        Run command in sandbox
        """
        pass

    def test_v1_sandbox_id_snapshot_post(self) -> None:
        """Test case for v1_sandbox_id_snapshot_post

        Create snapshot
        """
        pass

    def test_v1_sandbox_id_sshkey_post(self) -> None:
        """Test case for v1_sandbox_id_sshkey_post

        Inject SSH key into sandbox
        """
        pass

    def test_v1_sandbox_id_start_post(self) -> None:
        """Test case for v1_sandbox_id_start_post

        Start sandbox
        """
        pass


if __name__ == '__main__':
    unittest.main()
