# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.virsh_sandbox_internal_rest_run_command_response import VirshSandboxInternalRestRunCommandResponse

class TestVirshSandboxInternalRestRunCommandResponse(unittest.TestCase):
    """VirshSandboxInternalRestRunCommandResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VirshSandboxInternalRestRunCommandResponse:
        """Test VirshSandboxInternalRestRunCommandResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VirshSandboxInternalRestRunCommandResponse`
        """
        model = VirshSandboxInternalRestRunCommandResponse()
        if include_optional:
            return VirshSandboxInternalRestRunCommandResponse(
                command = openapi_client.models.virsh_sandbox_internal_store/command.virsh-sandbox_internal_store.Command(
                    command = '', 
                    ended_at = '', 
                    env_json = '', 
                    exit_code = 56, 
                    id = '', 
                    metadata = openapi_client.models.virsh_sandbox_internal_store/command_exec_record.virsh-sandbox_internal_store.CommandExecRecord(
                        redacted = {
                            'key' : ''
                            }, 
                        timeout = -9223372036854775808, 
                        user = '', 
                        work_dir = '', ), 
                    sandbox_id = '', 
                    started_at = '', 
                    stderr = '', 
                    stdout = '', )
            )
        else:
            return VirshSandboxInternalRestRunCommandResponse(
        )
        """

    def testVirshSandboxInternalRestRunCommandResponse(self):
        """Test VirshSandboxInternalRestRunCommandResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
