# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.virsh_sandbox_internal_rest_snapshot_response import VirshSandboxInternalRestSnapshotResponse

class TestVirshSandboxInternalRestSnapshotResponse(unittest.TestCase):
    """VirshSandboxInternalRestSnapshotResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VirshSandboxInternalRestSnapshotResponse:
        """Test VirshSandboxInternalRestSnapshotResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VirshSandboxInternalRestSnapshotResponse`
        """
        model = VirshSandboxInternalRestSnapshotResponse()
        if include_optional:
            return VirshSandboxInternalRestSnapshotResponse(
                snapshot = openapi_client.models.virsh_sandbox_internal_store/snapshot.virsh-sandbox_internal_store.Snapshot(
                    created_at = '', 
                    id = '', 
                    kind = 'INTERNAL', 
                    meta_json = '', 
                    name = '', 
                    ref = '', 
                    sandbox_id = '', )
            )
        else:
            return VirshSandboxInternalRestSnapshotResponse(
        )
        """

    def testVirshSandboxInternalRestSnapshotResponse(self):
        """Test VirshSandboxInternalRestSnapshotResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
