# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.internal_rest_diff_response import InternalRestDiffResponse

class TestInternalRestDiffResponse(unittest.TestCase):
    """InternalRestDiffResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalRestDiffResponse:
        """Test InternalRestDiffResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalRestDiffResponse`
        """
        model = InternalRestDiffResponse()
        if include_optional:
            return InternalRestDiffResponse(
                diff = openapi_client.models.virsh_sandbox_internal_store/diff.virsh-sandbox_internal_store.Diff(
                    created_at = '', 
                    diff_json = openapi_client.models.diff_json.diff_json(), 
                    from_snapshot = '', 
                    id = '', 
                    sandbox_id = '', 
                    to_snapshot = '', )
            )
        else:
            return InternalRestDiffResponse(
        )
        """

    def testInternalRestDiffResponse(self):
        """Test InternalRestDiffResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
