/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeleteV1PlanPlanID200,
  PostV1PlanPlanIDAbort200,
  PostV1PlanPlanIDAbortBody,
  PostV1PlanPlanIDAdvance200,
  PostV1PlanPlanIDAdvanceBody,
  TmuxClientInternalTypesAPIError,
  TmuxClientInternalTypesCreatePlanRequest,
  TmuxClientInternalTypesCreatePlanResponse,
  TmuxClientInternalTypesGetPlanResponse,
  TmuxClientInternalTypesListPlansResponse,
  TmuxClientInternalTypesUpdatePlanRequest,
  TmuxClientInternalTypesUpdatePlanResponse
} from '.././model';





/**
 * Lists all execution plans
 * @summary List plans
 */
export const getV1Plan = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesListPlansResponse>> => {
    
    
    return axios.default.get(
      `/v1/plan/`,options
    );
  }




export const getGetV1PlanQueryKey = () => {
    return [
    `/v1/plan/`
    ] as const;
    }

    
export const getGetV1PlanQueryOptions = <TData = Awaited<ReturnType<typeof getV1Plan>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Plan>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1PlanQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Plan>>> = ({ signal }) => getV1Plan({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1Plan>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1PlanQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Plan>>>
export type GetV1PlanQueryError = AxiosError<TmuxClientInternalTypesAPIError>


export function useGetV1Plan<TData = Awaited<ReturnType<typeof getV1Plan>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Plan>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Plan>>,
          TError,
          Awaited<ReturnType<typeof getV1Plan>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Plan<TData = Awaited<ReturnType<typeof getV1Plan>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Plan>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Plan>>,
          TError,
          Awaited<ReturnType<typeof getV1Plan>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Plan<TData = Awaited<ReturnType<typeof getV1Plan>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Plan>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List plans
 */

export function useGetV1Plan<TData = Awaited<ReturnType<typeof getV1Plan>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Plan>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1PlanQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Deletes an execution plan
 * @summary Delete plan
 */
export const deleteV1PlanPlanID = (
    planID: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteV1PlanPlanID200>> => {
    
    
    return axios.default.delete(
      `/v1/plan/${planID}`,options
    );
  }



export const getDeleteV1PlanPlanIDMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1PlanPlanID>>, TError,{planID: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1PlanPlanID>>, TError,{planID: string}, TContext> => {

const mutationKey = ['deleteV1PlanPlanID'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1PlanPlanID>>, {planID: string}> = (props) => {
          const {planID} = props ?? {};

          return  deleteV1PlanPlanID(planID,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1PlanPlanIDMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1PlanPlanID>>>
    
    export type DeleteV1PlanPlanIDMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Delete plan
 */
export const useDeleteV1PlanPlanID = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1PlanPlanID>>, TError,{planID: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1PlanPlanID>>,
        TError,
        {planID: string},
        TContext
      > => {

      const mutationOptions = getDeleteV1PlanPlanIDMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieves a specific execution plan
 * @summary Get plan
 */
export const getV1PlanPlanID = (
    planID: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesGetPlanResponse>> => {
    
    
    return axios.default.get(
      `/v1/plan/${planID}`,options
    );
  }




export const getGetV1PlanPlanIDQueryKey = (planID?: string,) => {
    return [
    `/v1/plan/${planID}`
    ] as const;
    }

    
export const getGetV1PlanPlanIDQueryOptions = <TData = Awaited<ReturnType<typeof getV1PlanPlanID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(planID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1PlanPlanID>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1PlanPlanIDQueryKey(planID);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1PlanPlanID>>> = ({ signal }) => getV1PlanPlanID(planID, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(planID), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1PlanPlanID>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1PlanPlanIDQueryResult = NonNullable<Awaited<ReturnType<typeof getV1PlanPlanID>>>
export type GetV1PlanPlanIDQueryError = AxiosError<TmuxClientInternalTypesAPIError>


export function useGetV1PlanPlanID<TData = Awaited<ReturnType<typeof getV1PlanPlanID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 planID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1PlanPlanID>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1PlanPlanID>>,
          TError,
          Awaited<ReturnType<typeof getV1PlanPlanID>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1PlanPlanID<TData = Awaited<ReturnType<typeof getV1PlanPlanID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 planID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1PlanPlanID>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1PlanPlanID>>,
          TError,
          Awaited<ReturnType<typeof getV1PlanPlanID>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1PlanPlanID<TData = Awaited<ReturnType<typeof getV1PlanPlanID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 planID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1PlanPlanID>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get plan
 */

export function useGetV1PlanPlanID<TData = Awaited<ReturnType<typeof getV1PlanPlanID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 planID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1PlanPlanID>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1PlanPlanIDQueryOptions(planID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Aborts an execution plan
 * @summary Abort plan
 */
export const postV1PlanPlanIDAbort = (
    planID: string,
    postV1PlanPlanIDAbortBody: PostV1PlanPlanIDAbortBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostV1PlanPlanIDAbort200>> => {
    
    
    return axios.default.post(
      `/v1/plan/${planID}/abort`,
      postV1PlanPlanIDAbortBody,options
    );
  }



export const getPostV1PlanPlanIDAbortMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1PlanPlanIDAbort>>, TError,{planID: string;data: PostV1PlanPlanIDAbortBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1PlanPlanIDAbort>>, TError,{planID: string;data: PostV1PlanPlanIDAbortBody}, TContext> => {

const mutationKey = ['postV1PlanPlanIDAbort'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1PlanPlanIDAbort>>, {planID: string;data: PostV1PlanPlanIDAbortBody}> = (props) => {
          const {planID,data} = props ?? {};

          return  postV1PlanPlanIDAbort(planID,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1PlanPlanIDAbortMutationResult = NonNullable<Awaited<ReturnType<typeof postV1PlanPlanIDAbort>>>
    export type PostV1PlanPlanIDAbortMutationBody = PostV1PlanPlanIDAbortBody
    export type PostV1PlanPlanIDAbortMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Abort plan
 */
export const usePostV1PlanPlanIDAbort = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1PlanPlanIDAbort>>, TError,{planID: string;data: PostV1PlanPlanIDAbortBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1PlanPlanIDAbort>>,
        TError,
        {planID: string;data: PostV1PlanPlanIDAbortBody},
        TContext
      > => {

      const mutationOptions = getPostV1PlanPlanIDAbortMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Advances to the next step in a plan
 * @summary Advance plan step
 */
export const postV1PlanPlanIDAdvance = (
    planID: string,
    postV1PlanPlanIDAdvanceBody: PostV1PlanPlanIDAdvanceBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostV1PlanPlanIDAdvance200>> => {
    
    
    return axios.default.post(
      `/v1/plan/${planID}/advance`,
      postV1PlanPlanIDAdvanceBody,options
    );
  }



export const getPostV1PlanPlanIDAdvanceMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1PlanPlanIDAdvance>>, TError,{planID: string;data: PostV1PlanPlanIDAdvanceBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1PlanPlanIDAdvance>>, TError,{planID: string;data: PostV1PlanPlanIDAdvanceBody}, TContext> => {

const mutationKey = ['postV1PlanPlanIDAdvance'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1PlanPlanIDAdvance>>, {planID: string;data: PostV1PlanPlanIDAdvanceBody}> = (props) => {
          const {planID,data} = props ?? {};

          return  postV1PlanPlanIDAdvance(planID,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1PlanPlanIDAdvanceMutationResult = NonNullable<Awaited<ReturnType<typeof postV1PlanPlanIDAdvance>>>
    export type PostV1PlanPlanIDAdvanceMutationBody = PostV1PlanPlanIDAdvanceBody
    export type PostV1PlanPlanIDAdvanceMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Advance plan step
 */
export const usePostV1PlanPlanIDAdvance = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1PlanPlanIDAdvance>>, TError,{planID: string;data: PostV1PlanPlanIDAdvanceBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1PlanPlanIDAdvance>>,
        TError,
        {planID: string;data: PostV1PlanPlanIDAdvanceBody},
        TContext
      > => {

      const mutationOptions = getPostV1PlanPlanIDAdvanceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a new execution plan
 * @summary Create plan
 */
export const postV1PlanCreate = (
    tmuxClientInternalTypesCreatePlanRequest: TmuxClientInternalTypesCreatePlanRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesCreatePlanResponse>> => {
    
    
    return axios.default.post(
      `/v1/plan/create`,
      tmuxClientInternalTypesCreatePlanRequest,options
    );
  }



export const getPostV1PlanCreateMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1PlanCreate>>, TError,{data: TmuxClientInternalTypesCreatePlanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1PlanCreate>>, TError,{data: TmuxClientInternalTypesCreatePlanRequest}, TContext> => {

const mutationKey = ['postV1PlanCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1PlanCreate>>, {data: TmuxClientInternalTypesCreatePlanRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1PlanCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1PlanCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postV1PlanCreate>>>
    export type PostV1PlanCreateMutationBody = TmuxClientInternalTypesCreatePlanRequest
    export type PostV1PlanCreateMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Create plan
 */
export const usePostV1PlanCreate = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1PlanCreate>>, TError,{data: TmuxClientInternalTypesCreatePlanRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1PlanCreate>>,
        TError,
        {data: TmuxClientInternalTypesCreatePlanRequest},
        TContext
      > => {

      const mutationOptions = getPostV1PlanCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Updates an execution plan
 * @summary Update plan
 */
export const postV1PlanUpdate = (
    tmuxClientInternalTypesUpdatePlanRequest: TmuxClientInternalTypesUpdatePlanRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesUpdatePlanResponse>> => {
    
    
    return axios.default.post(
      `/v1/plan/update`,
      tmuxClientInternalTypesUpdatePlanRequest,options
    );
  }



export const getPostV1PlanUpdateMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1PlanUpdate>>, TError,{data: TmuxClientInternalTypesUpdatePlanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1PlanUpdate>>, TError,{data: TmuxClientInternalTypesUpdatePlanRequest}, TContext> => {

const mutationKey = ['postV1PlanUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1PlanUpdate>>, {data: TmuxClientInternalTypesUpdatePlanRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1PlanUpdate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1PlanUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof postV1PlanUpdate>>>
    export type PostV1PlanUpdateMutationBody = TmuxClientInternalTypesUpdatePlanRequest
    export type PostV1PlanUpdateMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Update plan
 */
export const usePostV1PlanUpdate = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1PlanUpdate>>, TError,{data: TmuxClientInternalTypesUpdatePlanRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1PlanUpdate>>,
        TError,
        {data: TmuxClientInternalTypesUpdatePlanRequest},
        TContext
      > => {

      const mutationOptions = getPostV1PlanUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    