/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  InternalRestListVMsResponse
} from '.././model';


export const getGetApiV1VmsResponseMock = (overrideResponse: Partial< InternalRestListVMsResponse > = {}): InternalRestListVMsResponse => ({vms: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({disk_path: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), persistent: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), state: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), uuid: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])})), undefined]), ...overrideResponse})


export const getGetApiV1VmsMockHandler = (overrideResponse?: InternalRestListVMsResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<InternalRestListVMsResponse> | InternalRestListVMsResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/vms', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiV1VmsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getVmsMock = () => [
  getGetApiV1VmsMockHandler()
]
