# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing_extensions import Self


class InternalRestCertificateResponse(BaseModel):
    """
    InternalRestCertificateResponse
    """  # noqa: E501

    id: Optional[StrictStr] = None
    identity: Optional[StrictStr] = None
    is_expired: Optional[StrictBool] = None
    issued_at: Optional[StrictStr] = None
    principals: Optional[List[StrictStr]] = None
    sandbox_id: Optional[StrictStr] = None
    serial_number: Optional[StrictInt] = None
    status: Optional[StrictStr] = None
    ttl_seconds: Optional[StrictInt] = None
    user_id: Optional[StrictStr] = None
    valid_after: Optional[StrictStr] = None
    valid_before: Optional[StrictStr] = None
    vm_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "id",
        "identity",
        "is_expired",
        "issued_at",
        "principals",
        "sandbox_id",
        "serial_number",
        "status",
        "ttl_seconds",
        "user_id",
        "valid_after",
        "valid_before",
        "vm_id",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternalRestCertificateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternalRestCertificateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "identity": obj.get("identity"),
                "is_expired": obj.get("is_expired"),
                "issued_at": obj.get("issued_at"),
                "principals": obj.get("principals"),
                "sandbox_id": obj.get("sandbox_id"),
                "serial_number": obj.get("serial_number"),
                "status": obj.get("status"),
                "ttl_seconds": obj.get("ttl_seconds"),
                "user_id": obj.get("user_id"),
                "valid_after": obj.get("valid_after"),
                "valid_before": obj.get("valid_before"),
                "vm_id": obj.get("vm_id"),
            }
        )
        return _obj
