# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing_extensions import Self


class InternalRestSessionResponse(BaseModel):
    """
    InternalRestSessionResponse
    """  # noqa: E501

    certificate_id: Optional[StrictStr] = None
    duration_seconds: Optional[StrictInt] = None
    ended_at: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    sandbox_id: Optional[StrictStr] = None
    source_ip: Optional[StrictStr] = None
    started_at: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    user_id: Optional[StrictStr] = None
    vm_id: Optional[StrictStr] = None
    vm_ip_address: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "certificate_id",
        "duration_seconds",
        "ended_at",
        "id",
        "sandbox_id",
        "source_ip",
        "started_at",
        "status",
        "user_id",
        "vm_id",
        "vm_ip_address",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternalRestSessionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternalRestSessionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "certificate_id": obj.get("certificate_id"),
                "duration_seconds": obj.get("duration_seconds"),
                "ended_at": obj.get("ended_at"),
                "id": obj.get("id"),
                "sandbox_id": obj.get("sandbox_id"),
                "source_ip": obj.get("source_ip"),
                "started_at": obj.get("started_at"),
                "status": obj.get("status"),
                "user_id": obj.get("user_id"),
                "vm_id": obj.get("vm_id"),
                "vm_ip_address": obj.get("vm_ip_address"),
            }
        )
        return _obj
