/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export type TimeDuration = typeof TimeDuration[keyof typeof TimeDuration];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeDuration = {
  minDuration: -9223372036854776000,
  maxDuration: 9223372036854776000,
  Nanosecond: 1,
  Microsecond: 1000,
  Millisecond: 1000000,
  Second: 1000000000,
  Minute: 60000000000,
  Hour: 3600000000000,
} as const;
