/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export type VirshSandboxInternalStoreSnapshotKind = typeof VirshSandboxInternalStoreSnapshotKind[keyof typeof VirshSandboxInternalStoreSnapshotKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VirshSandboxInternalStoreSnapshotKind = {
  SnapshotKindInternal: 'INTERNAL',
  SnapshotKindExternal: 'EXTERNAL',
} as const;
