/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */
import type { VirshSandboxInternalStoreCommandExecRecord } from './virshSandboxInternalStoreCommandExecRecord';

export interface VirshSandboxInternalStoreCommand {
  command?: string;
  ended_at?: string;
  /** JSON-encoded env map */
  env_json?: string;
  exit_code?: number;
  id?: string;
  metadata?: VirshSandboxInternalStoreCommandExecRecord;
  sandbox_id?: string;
  started_at?: string;
  stderr?: string;
  stdout?: string;
}
