/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export type VirshSandboxInternalStoreSandboxState = typeof VirshSandboxInternalStoreSandboxState[keyof typeof VirshSandboxInternalStoreSandboxState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VirshSandboxInternalStoreSandboxState = {
  SandboxStateCreated: 'CREATED',
  SandboxStateStarting: 'STARTING',
  SandboxStateRunning: 'RUNNING',
  SandboxStateStopped: 'STOPPED',
  SandboxStateDestroyed: 'DESTROYED',
  SandboxStateError: 'ERROR',
} as const;
