/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export interface VirshSandboxInternalStoreServiceChange {
  enabled?: boolean;
  name?: string;
  /** started|stopped|restarted|reloaded */
  state?: string;
}
