/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetApiV1CommandAllowed200,
  TmuxClientInternalTypesAPIError,
  TmuxClientInternalTypesRunCommandRequest,
  TmuxClientInternalTypesRunCommandResponse
} from '.././model';





/**
 * Retrieves the list of allowed and denied commands
 * @summary Get allowed commands
 */
export const getApiV1CommandAllowed = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiV1CommandAllowed200>> => {
    
    
    return axios.default.get(
      `/api/v1/command/allowed`,options
    );
  }




export const getGetApiV1CommandAllowedQueryKey = () => {
    return [
    `/api/v1/command/allowed`
    ] as const;
    }

    
export const getGetApiV1CommandAllowedQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CommandAllowed>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommandAllowed>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CommandAllowedQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CommandAllowed>>> = ({ signal }) => getApiV1CommandAllowed({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommandAllowed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CommandAllowedQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CommandAllowed>>>
export type GetApiV1CommandAllowedQueryError = AxiosError<unknown>


export function useGetApiV1CommandAllowed<TData = Awaited<ReturnType<typeof getApiV1CommandAllowed>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommandAllowed>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CommandAllowed>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CommandAllowed>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CommandAllowed<TData = Awaited<ReturnType<typeof getApiV1CommandAllowed>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommandAllowed>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CommandAllowed>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CommandAllowed>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CommandAllowed<TData = Awaited<ReturnType<typeof getApiV1CommandAllowed>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommandAllowed>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get allowed commands
 */

export function useGetApiV1CommandAllowed<TData = Awaited<ReturnType<typeof getApiV1CommandAllowed>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommandAllowed>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CommandAllowedQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Executes a shell command
 * @summary Run command
 */
export const postApiV1CommandRun = (
    tmuxClientInternalTypesRunCommandRequest: TmuxClientInternalTypesRunCommandRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesRunCommandResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/command/run`,
      tmuxClientInternalTypesRunCommandRequest,options
    );
  }



export const getPostApiV1CommandRunMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommandRun>>, TError,{data: TmuxClientInternalTypesRunCommandRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommandRun>>, TError,{data: TmuxClientInternalTypesRunCommandRequest}, TContext> => {

const mutationKey = ['postApiV1CommandRun'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CommandRun>>, {data: TmuxClientInternalTypesRunCommandRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CommandRun(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CommandRunMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CommandRun>>>
    export type PostApiV1CommandRunMutationBody = TmuxClientInternalTypesRunCommandRequest
    export type PostApiV1CommandRunMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Run command
 */
export const usePostApiV1CommandRun = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommandRun>>, TError,{data: TmuxClientInternalTypesRunCommandRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CommandRun>>,
        TError,
        {data: TmuxClientInternalTypesRunCommandRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1CommandRunMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    