/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GetV1CommandAllowed200,
  TmuxClientInternalTypesRunCommandResponse
} from '.././model';


export const getGetV1CommandAllowedResponseMock = (): GetV1CommandAllowed200 => ({})

export const getPostV1CommandRunResponseMock = (overrideResponse: Partial< TmuxClientInternalTypesRunCommandResponse > = {}): TmuxClientInternalTypesRunCommandResponse => ({args: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined]), command: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), dry_run: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), duration_ms: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), exit_code: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), stderr: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), stdout: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), timed_out: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), ...overrideResponse})


export const getGetV1CommandAllowedMockHandler = (overrideResponse?: GetV1CommandAllowed200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetV1CommandAllowed200> | GetV1CommandAllowed200), options?: RequestHandlerOptions) => {
  return http.get('*/v1/command/allowed', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetV1CommandAllowedResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getPostV1CommandRunMockHandler = (overrideResponse?: TmuxClientInternalTypesRunCommandResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TmuxClientInternalTypesRunCommandResponse> | TmuxClientInternalTypesRunCommandResponse), options?: RequestHandlerOptions) => {
  return http.post('*/v1/command/run', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostV1CommandRunResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getCommandMock = () => [
  getGetV1CommandAllowedMockHandler(),
  getPostV1CommandRunMockHandler()
]
