/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export type InternalAnsibleJobStatus = typeof InternalAnsibleJobStatus[keyof typeof InternalAnsibleJobStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InternalAnsibleJobStatus = {
  JobStatusPending: 'pending',
  JobStatusRunning: 'running',
  JobStatusFinished: 'finished',
  JobStatusFailed: 'failed',
} as const;
