/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */
import type { VirshSandboxInternalRestRunCommandRequestEnv } from './virshSandboxInternalRestRunCommandRequestEnv';

export interface VirshSandboxInternalRestRunCommandRequest {
  /** required */
  command?: string;
  /** optional */
  env?: VirshSandboxInternalRestRunCommandRequestEnv;
  /** required; path on API host */
  private_key_path?: string;
  /** optional; default from service config */
  timeout_sec?: number;
  /** required */
  username?: string;
}
