/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */
import type { VirshSandboxInternalStoreCommandExecRecordRedacted } from './virshSandboxInternalStoreCommandExecRecordRedacted';
import type { TimeDuration } from './timeDuration';

export interface VirshSandboxInternalStoreCommandExecRecord {
  /** placeholders for secrets redaction */
  redacted?: VirshSandboxInternalStoreCommandExecRecordRedacted;
  timeout?: TimeDuration;
  user?: string;
  work_dir?: string;
}
