/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  PostApiV1FileExists200,
  PostApiV1FileExistsBody,
  PostApiV1FileHash200,
  PostApiV1FileHashBody,
  TmuxClientInternalTypesAPIError,
  TmuxClientInternalTypesCopyFileRequest,
  TmuxClientInternalTypesCopyFileResponse,
  TmuxClientInternalTypesDeleteFileRequest,
  TmuxClientInternalTypesDeleteFileResponse,
  TmuxClientInternalTypesEditFileRequest,
  TmuxClientInternalTypesEditFileResponse,
  TmuxClientInternalTypesListDirRequest,
  TmuxClientInternalTypesListDirResponse,
  TmuxClientInternalTypesReadFileRequest,
  TmuxClientInternalTypesReadFileResponse,
  TmuxClientInternalTypesWriteFileRequest,
  TmuxClientInternalTypesWriteFileResponse
} from '.././model';





/**
 * Copies a file from source to destination
 * @summary Copy file
 */
export const postApiV1FileCopy = (
    tmuxClientInternalTypesCopyFileRequest: TmuxClientInternalTypesCopyFileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesCopyFileResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/file/copy`,
      tmuxClientInternalTypesCopyFileRequest,options
    );
  }



export const getPostApiV1FileCopyMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileCopy>>, TError,{data: TmuxClientInternalTypesCopyFileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileCopy>>, TError,{data: TmuxClientInternalTypesCopyFileRequest}, TContext> => {

const mutationKey = ['postApiV1FileCopy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1FileCopy>>, {data: TmuxClientInternalTypesCopyFileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1FileCopy(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1FileCopyMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1FileCopy>>>
    export type PostApiV1FileCopyMutationBody = TmuxClientInternalTypesCopyFileRequest
    export type PostApiV1FileCopyMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Copy file
 */
export const usePostApiV1FileCopy = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileCopy>>, TError,{data: TmuxClientInternalTypesCopyFileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1FileCopy>>,
        TError,
        {data: TmuxClientInternalTypesCopyFileRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1FileCopyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Deletes a file or directory
 * @summary Delete file
 */
export const postApiV1FileDelete = (
    tmuxClientInternalTypesDeleteFileRequest: TmuxClientInternalTypesDeleteFileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesDeleteFileResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/file/delete`,
      tmuxClientInternalTypesDeleteFileRequest,options
    );
  }



export const getPostApiV1FileDeleteMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileDelete>>, TError,{data: TmuxClientInternalTypesDeleteFileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileDelete>>, TError,{data: TmuxClientInternalTypesDeleteFileRequest}, TContext> => {

const mutationKey = ['postApiV1FileDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1FileDelete>>, {data: TmuxClientInternalTypesDeleteFileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1FileDelete(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1FileDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1FileDelete>>>
    export type PostApiV1FileDeleteMutationBody = TmuxClientInternalTypesDeleteFileRequest
    export type PostApiV1FileDeleteMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Delete file
 */
export const usePostApiV1FileDelete = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileDelete>>, TError,{data: TmuxClientInternalTypesDeleteFileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1FileDelete>>,
        TError,
        {data: TmuxClientInternalTypesDeleteFileRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1FileDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Edits the content of a file
 * @summary Edit file
 */
export const postApiV1FileEdit = (
    tmuxClientInternalTypesEditFileRequest: TmuxClientInternalTypesEditFileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesEditFileResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/file/edit`,
      tmuxClientInternalTypesEditFileRequest,options
    );
  }



export const getPostApiV1FileEditMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileEdit>>, TError,{data: TmuxClientInternalTypesEditFileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileEdit>>, TError,{data: TmuxClientInternalTypesEditFileRequest}, TContext> => {

const mutationKey = ['postApiV1FileEdit'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1FileEdit>>, {data: TmuxClientInternalTypesEditFileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1FileEdit(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1FileEditMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1FileEdit>>>
    export type PostApiV1FileEditMutationBody = TmuxClientInternalTypesEditFileRequest
    export type PostApiV1FileEditMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Edit file
 */
export const usePostApiV1FileEdit = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileEdit>>, TError,{data: TmuxClientInternalTypesEditFileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1FileEdit>>,
        TError,
        {data: TmuxClientInternalTypesEditFileRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1FileEditMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Checks if a file or directory exists
 * @summary Check if file exists
 */
export const postApiV1FileExists = (
    postApiV1FileExistsBody: PostApiV1FileExistsBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiV1FileExists200>> => {
    
    
    return axios.default.post(
      `/api/v1/file/exists`,
      postApiV1FileExistsBody,options
    );
  }



export const getPostApiV1FileExistsMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileExists>>, TError,{data: PostApiV1FileExistsBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileExists>>, TError,{data: PostApiV1FileExistsBody}, TContext> => {

const mutationKey = ['postApiV1FileExists'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1FileExists>>, {data: PostApiV1FileExistsBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1FileExists(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1FileExistsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1FileExists>>>
    export type PostApiV1FileExistsMutationBody = PostApiV1FileExistsBody
    export type PostApiV1FileExistsMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Check if file exists
 */
export const usePostApiV1FileExists = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileExists>>, TError,{data: PostApiV1FileExistsBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1FileExists>>,
        TError,
        {data: PostApiV1FileExistsBody},
        TContext
      > => {

      const mutationOptions = getPostApiV1FileExistsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Computes the SHA256 hash of a file
 * @summary Get file hash
 */
export const postApiV1FileHash = (
    postApiV1FileHashBody: PostApiV1FileHashBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiV1FileHash200>> => {
    
    
    return axios.default.post(
      `/api/v1/file/hash`,
      postApiV1FileHashBody,options
    );
  }



export const getPostApiV1FileHashMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileHash>>, TError,{data: PostApiV1FileHashBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileHash>>, TError,{data: PostApiV1FileHashBody}, TContext> => {

const mutationKey = ['postApiV1FileHash'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1FileHash>>, {data: PostApiV1FileHashBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1FileHash(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1FileHashMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1FileHash>>>
    export type PostApiV1FileHashMutationBody = PostApiV1FileHashBody
    export type PostApiV1FileHashMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Get file hash
 */
export const usePostApiV1FileHash = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileHash>>, TError,{data: PostApiV1FileHashBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1FileHash>>,
        TError,
        {data: PostApiV1FileHashBody},
        TContext
      > => {

      const mutationOptions = getPostApiV1FileHashMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Lists the contents of a directory
 * @summary List directory contents
 */
export const postApiV1FileList = (
    tmuxClientInternalTypesListDirRequest: TmuxClientInternalTypesListDirRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesListDirResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/file/list`,
      tmuxClientInternalTypesListDirRequest,options
    );
  }



export const getPostApiV1FileListMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileList>>, TError,{data: TmuxClientInternalTypesListDirRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileList>>, TError,{data: TmuxClientInternalTypesListDirRequest}, TContext> => {

const mutationKey = ['postApiV1FileList'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1FileList>>, {data: TmuxClientInternalTypesListDirRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1FileList(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1FileListMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1FileList>>>
    export type PostApiV1FileListMutationBody = TmuxClientInternalTypesListDirRequest
    export type PostApiV1FileListMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary List directory contents
 */
export const usePostApiV1FileList = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileList>>, TError,{data: TmuxClientInternalTypesListDirRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1FileList>>,
        TError,
        {data: TmuxClientInternalTypesListDirRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1FileListMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Reads the content of a file
 * @summary Read file
 */
export const postApiV1FileRead = (
    tmuxClientInternalTypesReadFileRequest: TmuxClientInternalTypesReadFileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesReadFileResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/file/read`,
      tmuxClientInternalTypesReadFileRequest,options
    );
  }



export const getPostApiV1FileReadMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileRead>>, TError,{data: TmuxClientInternalTypesReadFileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileRead>>, TError,{data: TmuxClientInternalTypesReadFileRequest}, TContext> => {

const mutationKey = ['postApiV1FileRead'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1FileRead>>, {data: TmuxClientInternalTypesReadFileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1FileRead(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1FileReadMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1FileRead>>>
    export type PostApiV1FileReadMutationBody = TmuxClientInternalTypesReadFileRequest
    export type PostApiV1FileReadMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Read file
 */
export const usePostApiV1FileRead = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileRead>>, TError,{data: TmuxClientInternalTypesReadFileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1FileRead>>,
        TError,
        {data: TmuxClientInternalTypesReadFileRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1FileReadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Writes content to a file
 * @summary Write file
 */
export const postApiV1FileWrite = (
    tmuxClientInternalTypesWriteFileRequest: TmuxClientInternalTypesWriteFileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesWriteFileResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/file/write`,
      tmuxClientInternalTypesWriteFileRequest,options
    );
  }



export const getPostApiV1FileWriteMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileWrite>>, TError,{data: TmuxClientInternalTypesWriteFileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileWrite>>, TError,{data: TmuxClientInternalTypesWriteFileRequest}, TContext> => {

const mutationKey = ['postApiV1FileWrite'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1FileWrite>>, {data: TmuxClientInternalTypesWriteFileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1FileWrite(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1FileWriteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1FileWrite>>>
    export type PostApiV1FileWriteMutationBody = TmuxClientInternalTypesWriteFileRequest
    export type PostApiV1FileWriteMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Write file
 */
export const usePostApiV1FileWrite = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1FileWrite>>, TError,{data: TmuxClientInternalTypesWriteFileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1FileWrite>>,
        TError,
        {data: TmuxClientInternalTypesWriteFileRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1FileWriteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    