/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeleteApiV1PlanPlanID200,
  PostApiV1PlanPlanIDAbort200,
  PostApiV1PlanPlanIDAbortBody,
  PostApiV1PlanPlanIDAdvance200,
  PostApiV1PlanPlanIDAdvanceBody,
  TmuxClientInternalTypesAPIError,
  TmuxClientInternalTypesCreatePlanRequest,
  TmuxClientInternalTypesCreatePlanResponse,
  TmuxClientInternalTypesGetPlanResponse,
  TmuxClientInternalTypesListPlansResponse,
  TmuxClientInternalTypesUpdatePlanRequest,
  TmuxClientInternalTypesUpdatePlanResponse
} from '.././model';





/**
 * Lists all execution plans
 * @summary List plans
 */
export const getApiV1Plan = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesListPlansResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/plan/`,options
    );
  }




export const getGetApiV1PlanQueryKey = () => {
    return [
    `/api/v1/plan/`
    ] as const;
    }

    
export const getGetApiV1PlanQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Plan>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Plan>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PlanQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Plan>>> = ({ signal }) => getApiV1Plan({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Plan>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PlanQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Plan>>>
export type GetApiV1PlanQueryError = AxiosError<TmuxClientInternalTypesAPIError>


export function useGetApiV1Plan<TData = Awaited<ReturnType<typeof getApiV1Plan>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Plan>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Plan>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Plan>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Plan<TData = Awaited<ReturnType<typeof getApiV1Plan>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Plan>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Plan>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Plan>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Plan<TData = Awaited<ReturnType<typeof getApiV1Plan>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Plan>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List plans
 */

export function useGetApiV1Plan<TData = Awaited<ReturnType<typeof getApiV1Plan>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Plan>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PlanQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Deletes an execution plan
 * @summary Delete plan
 */
export const deleteApiV1PlanPlanID = (
    planID: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteApiV1PlanPlanID200>> => {
    
    
    return axios.default.delete(
      `/api/v1/plan/${planID}`,options
    );
  }



export const getDeleteApiV1PlanPlanIDMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1PlanPlanID>>, TError,{planID: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1PlanPlanID>>, TError,{planID: string}, TContext> => {

const mutationKey = ['deleteApiV1PlanPlanID'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1PlanPlanID>>, {planID: string}> = (props) => {
          const {planID} = props ?? {};

          return  deleteApiV1PlanPlanID(planID,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1PlanPlanIDMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1PlanPlanID>>>
    
    export type DeleteApiV1PlanPlanIDMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Delete plan
 */
export const useDeleteApiV1PlanPlanID = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1PlanPlanID>>, TError,{planID: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1PlanPlanID>>,
        TError,
        {planID: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1PlanPlanIDMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieves a specific execution plan
 * @summary Get plan
 */
export const getApiV1PlanPlanID = (
    planID: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesGetPlanResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/plan/${planID}`,options
    );
  }




export const getGetApiV1PlanPlanIDQueryKey = (planID?: string,) => {
    return [
    `/api/v1/plan/${planID}`
    ] as const;
    }

    
export const getGetApiV1PlanPlanIDQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PlanPlanID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(planID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlanPlanID>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PlanPlanIDQueryKey(planID);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PlanPlanID>>> = ({ signal }) => getApiV1PlanPlanID(planID, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(planID), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlanPlanID>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PlanPlanIDQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PlanPlanID>>>
export type GetApiV1PlanPlanIDQueryError = AxiosError<TmuxClientInternalTypesAPIError>


export function useGetApiV1PlanPlanID<TData = Awaited<ReturnType<typeof getApiV1PlanPlanID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 planID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlanPlanID>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PlanPlanID>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PlanPlanID>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PlanPlanID<TData = Awaited<ReturnType<typeof getApiV1PlanPlanID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 planID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlanPlanID>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PlanPlanID>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PlanPlanID>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PlanPlanID<TData = Awaited<ReturnType<typeof getApiV1PlanPlanID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 planID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlanPlanID>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get plan
 */

export function useGetApiV1PlanPlanID<TData = Awaited<ReturnType<typeof getApiV1PlanPlanID>>, TError = AxiosError<TmuxClientInternalTypesAPIError>>(
 planID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlanPlanID>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PlanPlanIDQueryOptions(planID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Aborts an execution plan
 * @summary Abort plan
 */
export const postApiV1PlanPlanIDAbort = (
    planID: string,
    postApiV1PlanPlanIDAbortBody: PostApiV1PlanPlanIDAbortBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiV1PlanPlanIDAbort200>> => {
    
    
    return axios.default.post(
      `/api/v1/plan/${planID}/abort`,
      postApiV1PlanPlanIDAbortBody,options
    );
  }



export const getPostApiV1PlanPlanIDAbortMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlanPlanIDAbort>>, TError,{planID: string;data: PostApiV1PlanPlanIDAbortBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlanPlanIDAbort>>, TError,{planID: string;data: PostApiV1PlanPlanIDAbortBody}, TContext> => {

const mutationKey = ['postApiV1PlanPlanIDAbort'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PlanPlanIDAbort>>, {planID: string;data: PostApiV1PlanPlanIDAbortBody}> = (props) => {
          const {planID,data} = props ?? {};

          return  postApiV1PlanPlanIDAbort(planID,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PlanPlanIDAbortMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PlanPlanIDAbort>>>
    export type PostApiV1PlanPlanIDAbortMutationBody = PostApiV1PlanPlanIDAbortBody
    export type PostApiV1PlanPlanIDAbortMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Abort plan
 */
export const usePostApiV1PlanPlanIDAbort = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlanPlanIDAbort>>, TError,{planID: string;data: PostApiV1PlanPlanIDAbortBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PlanPlanIDAbort>>,
        TError,
        {planID: string;data: PostApiV1PlanPlanIDAbortBody},
        TContext
      > => {

      const mutationOptions = getPostApiV1PlanPlanIDAbortMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Advances to the next step in a plan
 * @summary Advance plan step
 */
export const postApiV1PlanPlanIDAdvance = (
    planID: string,
    postApiV1PlanPlanIDAdvanceBody: PostApiV1PlanPlanIDAdvanceBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiV1PlanPlanIDAdvance200>> => {
    
    
    return axios.default.post(
      `/api/v1/plan/${planID}/advance`,
      postApiV1PlanPlanIDAdvanceBody,options
    );
  }



export const getPostApiV1PlanPlanIDAdvanceMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlanPlanIDAdvance>>, TError,{planID: string;data: PostApiV1PlanPlanIDAdvanceBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlanPlanIDAdvance>>, TError,{planID: string;data: PostApiV1PlanPlanIDAdvanceBody}, TContext> => {

const mutationKey = ['postApiV1PlanPlanIDAdvance'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PlanPlanIDAdvance>>, {planID: string;data: PostApiV1PlanPlanIDAdvanceBody}> = (props) => {
          const {planID,data} = props ?? {};

          return  postApiV1PlanPlanIDAdvance(planID,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PlanPlanIDAdvanceMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PlanPlanIDAdvance>>>
    export type PostApiV1PlanPlanIDAdvanceMutationBody = PostApiV1PlanPlanIDAdvanceBody
    export type PostApiV1PlanPlanIDAdvanceMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Advance plan step
 */
export const usePostApiV1PlanPlanIDAdvance = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlanPlanIDAdvance>>, TError,{planID: string;data: PostApiV1PlanPlanIDAdvanceBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PlanPlanIDAdvance>>,
        TError,
        {planID: string;data: PostApiV1PlanPlanIDAdvanceBody},
        TContext
      > => {

      const mutationOptions = getPostApiV1PlanPlanIDAdvanceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a new execution plan
 * @summary Create plan
 */
export const postApiV1PlanCreate = (
    tmuxClientInternalTypesCreatePlanRequest: TmuxClientInternalTypesCreatePlanRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesCreatePlanResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/plan/create`,
      tmuxClientInternalTypesCreatePlanRequest,options
    );
  }



export const getPostApiV1PlanCreateMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlanCreate>>, TError,{data: TmuxClientInternalTypesCreatePlanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlanCreate>>, TError,{data: TmuxClientInternalTypesCreatePlanRequest}, TContext> => {

const mutationKey = ['postApiV1PlanCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PlanCreate>>, {data: TmuxClientInternalTypesCreatePlanRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1PlanCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PlanCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PlanCreate>>>
    export type PostApiV1PlanCreateMutationBody = TmuxClientInternalTypesCreatePlanRequest
    export type PostApiV1PlanCreateMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Create plan
 */
export const usePostApiV1PlanCreate = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlanCreate>>, TError,{data: TmuxClientInternalTypesCreatePlanRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PlanCreate>>,
        TError,
        {data: TmuxClientInternalTypesCreatePlanRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1PlanCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Updates an execution plan
 * @summary Update plan
 */
export const postApiV1PlanUpdate = (
    tmuxClientInternalTypesUpdatePlanRequest: TmuxClientInternalTypesUpdatePlanRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesUpdatePlanResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/plan/update`,
      tmuxClientInternalTypesUpdatePlanRequest,options
    );
  }



export const getPostApiV1PlanUpdateMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlanUpdate>>, TError,{data: TmuxClientInternalTypesUpdatePlanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlanUpdate>>, TError,{data: TmuxClientInternalTypesUpdatePlanRequest}, TContext> => {

const mutationKey = ['postApiV1PlanUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PlanUpdate>>, {data: TmuxClientInternalTypesUpdatePlanRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1PlanUpdate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PlanUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PlanUpdate>>>
    export type PostApiV1PlanUpdateMutationBody = TmuxClientInternalTypesUpdatePlanRequest
    export type PostApiV1PlanUpdateMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Update plan
 */
export const usePostApiV1PlanUpdate = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlanUpdate>>, TError,{data: TmuxClientInternalTypesUpdatePlanRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PlanUpdate>>,
        TError,
        {data: TmuxClientInternalTypesUpdatePlanRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1PlanUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    