/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import type { TmuxClientInternalTypesPlanStatus } from './tmuxClientInternalTypesPlanStatus';
import type { TmuxClientInternalTypesPlanStep } from './tmuxClientInternalTypesPlanStep';

export interface TmuxClientInternalTypesPlan {
  completed_at?: string;
  created_at?: string;
  /** -1 if not started */
  current_step?: number;
  description?: string;
  id?: string;
  name?: string;
  status?: TmuxClientInternalTypesPlanStatus;
  steps?: TmuxClientInternalTypesPlanStep[];
  updated_at?: string;
}
