/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */

export type TmuxClientInternalTypesApprovalStatus = typeof TmuxClientInternalTypesApprovalStatus[keyof typeof TmuxClientInternalTypesApprovalStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TmuxClientInternalTypesApprovalStatus = {
  ApprovalPending: 'pending',
  ApprovalApproved: 'approved',
  ApprovalRejected: 'rejected',
  ApprovalExpired: 'expired',
} as const;
