/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */

export interface TmuxClientInternalTypesRunCommandRequest {
  /** Arguments as separate items */
  args?: string[];
  /** Executable name only */
  command?: string;
  /** If true, don't actually run */
  dry_run?: boolean;
  /** Additional env vars (KEY=VALUE) */
  env?: string[];
  /** Seconds, 0 = default (30s) */
  timeout?: number;
  /** Working directory */
  work_dir?: string;
}
