/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import type { TmuxClientInternalTypesPlan } from './tmuxClientInternalTypesPlan';

export interface TmuxClientInternalTypesUpdatePlanResponse {
  plan?: TmuxClientInternalTypesPlan;
  plan_id?: string;
  updated?: boolean;
}
