/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */

export interface TmuxClientInternalTypesReadFileResponse {
  content?: string;
  from_line?: number;
  mod_time?: string;
  mode?: string;
  path?: string;
  size?: number;
  to_line?: number;
  total_lines?: number;
  truncated?: boolean;
}
