/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import type { TmuxClientInternalTypesAPIError } from './tmuxClientInternalTypesAPIError';

export interface TmuxClientInternalTypesAuditEntry {
  action?: string;
  arguments?: number[];
  client_ip?: string;
  duration_ms?: number;
  error?: TmuxClientInternalTypesAPIError;
  request_id?: string;
  result?: number[];
  timestamp?: string;
  tool?: string;
  user_agent?: string;
}
