/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */

export type TmuxClientInternalTypesHealthStatus = typeof TmuxClientInternalTypesHealthStatus[keyof typeof TmuxClientInternalTypesHealthStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TmuxClientInternalTypesHealthStatus = {
  HealthStatusHealthy: 'healthy',
  HealthStatusDegraded: 'degraded',
  HealthStatusUnhealthy: 'unhealthy',
} as const;
