/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import type { TmuxClientInternalTypesStepStatus } from './tmuxClientInternalTypesStepStatus';

export interface TmuxClientInternalTypesUpdatePlanRequest {
  error?: string;
  plan_id?: string;
  result?: string;
  status?: TmuxClientInternalTypesStepStatus;
  step_index?: number;
}
