/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  PostV1FileExists200,
  PostV1FileExistsBody,
  PostV1FileHash200,
  PostV1FileHashBody,
  TmuxClientInternalTypesAPIError,
  TmuxClientInternalTypesCopyFileRequest,
  TmuxClientInternalTypesCopyFileResponse,
  TmuxClientInternalTypesDeleteFileRequest,
  TmuxClientInternalTypesDeleteFileResponse,
  TmuxClientInternalTypesEditFileRequest,
  TmuxClientInternalTypesEditFileResponse,
  TmuxClientInternalTypesListDirRequest,
  TmuxClientInternalTypesListDirResponse,
  TmuxClientInternalTypesReadFileRequest,
  TmuxClientInternalTypesReadFileResponse,
  TmuxClientInternalTypesWriteFileRequest,
  TmuxClientInternalTypesWriteFileResponse
} from '.././model';





/**
 * Copies a file from source to destination
 * @summary Copy file
 */
export const postV1FileCopy = (
    tmuxClientInternalTypesCopyFileRequest: TmuxClientInternalTypesCopyFileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesCopyFileResponse>> => {
    
    
    return axios.default.post(
      `/v1/file/copy`,
      tmuxClientInternalTypesCopyFileRequest,options
    );
  }



export const getPostV1FileCopyMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileCopy>>, TError,{data: TmuxClientInternalTypesCopyFileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FileCopy>>, TError,{data: TmuxClientInternalTypesCopyFileRequest}, TContext> => {

const mutationKey = ['postV1FileCopy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FileCopy>>, {data: TmuxClientInternalTypesCopyFileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1FileCopy(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1FileCopyMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FileCopy>>>
    export type PostV1FileCopyMutationBody = TmuxClientInternalTypesCopyFileRequest
    export type PostV1FileCopyMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Copy file
 */
export const usePostV1FileCopy = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileCopy>>, TError,{data: TmuxClientInternalTypesCopyFileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1FileCopy>>,
        TError,
        {data: TmuxClientInternalTypesCopyFileRequest},
        TContext
      > => {

      const mutationOptions = getPostV1FileCopyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Deletes a file or directory
 * @summary Delete file
 */
export const postV1FileDelete = (
    tmuxClientInternalTypesDeleteFileRequest: TmuxClientInternalTypesDeleteFileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesDeleteFileResponse>> => {
    
    
    return axios.default.post(
      `/v1/file/delete`,
      tmuxClientInternalTypesDeleteFileRequest,options
    );
  }



export const getPostV1FileDeleteMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileDelete>>, TError,{data: TmuxClientInternalTypesDeleteFileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FileDelete>>, TError,{data: TmuxClientInternalTypesDeleteFileRequest}, TContext> => {

const mutationKey = ['postV1FileDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FileDelete>>, {data: TmuxClientInternalTypesDeleteFileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1FileDelete(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1FileDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FileDelete>>>
    export type PostV1FileDeleteMutationBody = TmuxClientInternalTypesDeleteFileRequest
    export type PostV1FileDeleteMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Delete file
 */
export const usePostV1FileDelete = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileDelete>>, TError,{data: TmuxClientInternalTypesDeleteFileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1FileDelete>>,
        TError,
        {data: TmuxClientInternalTypesDeleteFileRequest},
        TContext
      > => {

      const mutationOptions = getPostV1FileDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Edits the content of a file
 * @summary Edit file
 */
export const postV1FileEdit = (
    tmuxClientInternalTypesEditFileRequest: TmuxClientInternalTypesEditFileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesEditFileResponse>> => {
    
    
    return axios.default.post(
      `/v1/file/edit`,
      tmuxClientInternalTypesEditFileRequest,options
    );
  }



export const getPostV1FileEditMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileEdit>>, TError,{data: TmuxClientInternalTypesEditFileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FileEdit>>, TError,{data: TmuxClientInternalTypesEditFileRequest}, TContext> => {

const mutationKey = ['postV1FileEdit'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FileEdit>>, {data: TmuxClientInternalTypesEditFileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1FileEdit(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1FileEditMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FileEdit>>>
    export type PostV1FileEditMutationBody = TmuxClientInternalTypesEditFileRequest
    export type PostV1FileEditMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Edit file
 */
export const usePostV1FileEdit = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileEdit>>, TError,{data: TmuxClientInternalTypesEditFileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1FileEdit>>,
        TError,
        {data: TmuxClientInternalTypesEditFileRequest},
        TContext
      > => {

      const mutationOptions = getPostV1FileEditMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Checks if a file or directory exists
 * @summary Check if file exists
 */
export const postV1FileExists = (
    postV1FileExistsBody: PostV1FileExistsBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostV1FileExists200>> => {
    
    
    return axios.default.post(
      `/v1/file/exists`,
      postV1FileExistsBody,options
    );
  }



export const getPostV1FileExistsMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileExists>>, TError,{data: PostV1FileExistsBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FileExists>>, TError,{data: PostV1FileExistsBody}, TContext> => {

const mutationKey = ['postV1FileExists'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FileExists>>, {data: PostV1FileExistsBody}> = (props) => {
          const {data} = props ?? {};

          return  postV1FileExists(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1FileExistsMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FileExists>>>
    export type PostV1FileExistsMutationBody = PostV1FileExistsBody
    export type PostV1FileExistsMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Check if file exists
 */
export const usePostV1FileExists = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileExists>>, TError,{data: PostV1FileExistsBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1FileExists>>,
        TError,
        {data: PostV1FileExistsBody},
        TContext
      > => {

      const mutationOptions = getPostV1FileExistsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Computes the SHA256 hash of a file
 * @summary Get file hash
 */
export const postV1FileHash = (
    postV1FileHashBody: PostV1FileHashBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostV1FileHash200>> => {
    
    
    return axios.default.post(
      `/v1/file/hash`,
      postV1FileHashBody,options
    );
  }



export const getPostV1FileHashMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileHash>>, TError,{data: PostV1FileHashBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FileHash>>, TError,{data: PostV1FileHashBody}, TContext> => {

const mutationKey = ['postV1FileHash'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FileHash>>, {data: PostV1FileHashBody}> = (props) => {
          const {data} = props ?? {};

          return  postV1FileHash(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1FileHashMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FileHash>>>
    export type PostV1FileHashMutationBody = PostV1FileHashBody
    export type PostV1FileHashMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Get file hash
 */
export const usePostV1FileHash = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileHash>>, TError,{data: PostV1FileHashBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1FileHash>>,
        TError,
        {data: PostV1FileHashBody},
        TContext
      > => {

      const mutationOptions = getPostV1FileHashMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Lists the contents of a directory
 * @summary List directory contents
 */
export const postV1FileList = (
    tmuxClientInternalTypesListDirRequest: TmuxClientInternalTypesListDirRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesListDirResponse>> => {
    
    
    return axios.default.post(
      `/v1/file/list`,
      tmuxClientInternalTypesListDirRequest,options
    );
  }



export const getPostV1FileListMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileList>>, TError,{data: TmuxClientInternalTypesListDirRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FileList>>, TError,{data: TmuxClientInternalTypesListDirRequest}, TContext> => {

const mutationKey = ['postV1FileList'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FileList>>, {data: TmuxClientInternalTypesListDirRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1FileList(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1FileListMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FileList>>>
    export type PostV1FileListMutationBody = TmuxClientInternalTypesListDirRequest
    export type PostV1FileListMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary List directory contents
 */
export const usePostV1FileList = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileList>>, TError,{data: TmuxClientInternalTypesListDirRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1FileList>>,
        TError,
        {data: TmuxClientInternalTypesListDirRequest},
        TContext
      > => {

      const mutationOptions = getPostV1FileListMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Reads the content of a file
 * @summary Read file
 */
export const postV1FileRead = (
    tmuxClientInternalTypesReadFileRequest: TmuxClientInternalTypesReadFileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesReadFileResponse>> => {
    
    
    return axios.default.post(
      `/v1/file/read`,
      tmuxClientInternalTypesReadFileRequest,options
    );
  }



export const getPostV1FileReadMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileRead>>, TError,{data: TmuxClientInternalTypesReadFileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FileRead>>, TError,{data: TmuxClientInternalTypesReadFileRequest}, TContext> => {

const mutationKey = ['postV1FileRead'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FileRead>>, {data: TmuxClientInternalTypesReadFileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1FileRead(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1FileReadMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FileRead>>>
    export type PostV1FileReadMutationBody = TmuxClientInternalTypesReadFileRequest
    export type PostV1FileReadMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Read file
 */
export const usePostV1FileRead = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileRead>>, TError,{data: TmuxClientInternalTypesReadFileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1FileRead>>,
        TError,
        {data: TmuxClientInternalTypesReadFileRequest},
        TContext
      > => {

      const mutationOptions = getPostV1FileReadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Writes content to a file
 * @summary Write file
 */
export const postV1FileWrite = (
    tmuxClientInternalTypesWriteFileRequest: TmuxClientInternalTypesWriteFileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TmuxClientInternalTypesWriteFileResponse>> => {
    
    
    return axios.default.post(
      `/v1/file/write`,
      tmuxClientInternalTypesWriteFileRequest,options
    );
  }



export const getPostV1FileWriteMutationOptions = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileWrite>>, TError,{data: TmuxClientInternalTypesWriteFileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FileWrite>>, TError,{data: TmuxClientInternalTypesWriteFileRequest}, TContext> => {

const mutationKey = ['postV1FileWrite'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FileWrite>>, {data: TmuxClientInternalTypesWriteFileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1FileWrite(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1FileWriteMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FileWrite>>>
    export type PostV1FileWriteMutationBody = TmuxClientInternalTypesWriteFileRequest
    export type PostV1FileWriteMutationError = AxiosError<TmuxClientInternalTypesAPIError>

    /**
 * @summary Write file
 */
export const usePostV1FileWrite = <TError = AxiosError<TmuxClientInternalTypesAPIError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FileWrite>>, TError,{data: TmuxClientInternalTypesWriteFileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1FileWrite>>,
        TError,
        {data: TmuxClientInternalTypesWriteFileRequest},
        TContext
      > => {

      const mutationOptions = getPostV1FileWriteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    