/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  VirshSandboxInternalRestCreateSandboxRequest,
  VirshSandboxInternalRestCreateSandboxResponse,
  VirshSandboxInternalRestDiffRequest,
  VirshSandboxInternalRestDiffResponse,
  VirshSandboxInternalRestErrorResponse,
  VirshSandboxInternalRestGenerateResponse,
  VirshSandboxInternalRestInjectSSHKeyRequest,
  VirshSandboxInternalRestPublishRequest,
  VirshSandboxInternalRestPublishResponse,
  VirshSandboxInternalRestRunCommandRequest,
  VirshSandboxInternalRestRunCommandResponse,
  VirshSandboxInternalRestSnapshotRequest,
  VirshSandboxInternalRestSnapshotResponse,
  VirshSandboxInternalRestStartSandboxRequest,
  VirshSandboxInternalRestStartSandboxResponse
} from '.././model';





/**
 * Destroys the sandbox and cleans up resources
 * @summary Destroy sandbox
 */
export const deleteApiV1SandboxId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/v1/sandbox/${id}`,options
    );
  }



export const getDeleteApiV1SandboxIdMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1SandboxId>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1SandboxId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1SandboxId'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1SandboxId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1SandboxId(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1SandboxIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1SandboxId>>>
    
    export type DeleteApiV1SandboxIdMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Destroy sandbox
 */
export const useDeleteApiV1SandboxId = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1SandboxId>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1SandboxId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1SandboxIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Computes differences between two snapshots
 * @summary Diff snapshots
 */
export const postApiV1SandboxIdDiff = (
    id: string,
    virshSandboxInternalRestDiffRequest: VirshSandboxInternalRestDiffRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VirshSandboxInternalRestDiffResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/sandbox/${id}/diff`,
      virshSandboxInternalRestDiffRequest,options
    );
  }



export const getPostApiV1SandboxIdDiffMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdDiff>>, TError,{id: string;data: VirshSandboxInternalRestDiffRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdDiff>>, TError,{id: string;data: VirshSandboxInternalRestDiffRequest}, TContext> => {

const mutationKey = ['postApiV1SandboxIdDiff'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SandboxIdDiff>>, {id: string;data: VirshSandboxInternalRestDiffRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SandboxIdDiff(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SandboxIdDiffMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SandboxIdDiff>>>
    export type PostApiV1SandboxIdDiffMutationBody = VirshSandboxInternalRestDiffRequest
    export type PostApiV1SandboxIdDiffMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Diff snapshots
 */
export const usePostApiV1SandboxIdDiff = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdDiff>>, TError,{id: string;data: VirshSandboxInternalRestDiffRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SandboxIdDiff>>,
        TError,
        {id: string;data: VirshSandboxInternalRestDiffRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1SandboxIdDiffMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Generates Ansible or Puppet configuration from sandbox changes
 * @summary Generate configuration
 */
export const postApiV1SandboxIdGenerateTool = (
    id: string,
    tool: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/v1/sandbox/${id}/generate/${tool}`,undefined,options
    );
  }



export const getPostApiV1SandboxIdGenerateToolMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse | VirshSandboxInternalRestGenerateResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdGenerateTool>>, TError,{id: string;tool: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdGenerateTool>>, TError,{id: string;tool: string}, TContext> => {

const mutationKey = ['postApiV1SandboxIdGenerateTool'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SandboxIdGenerateTool>>, {id: string;tool: string}> = (props) => {
          const {id,tool} = props ?? {};

          return  postApiV1SandboxIdGenerateTool(id,tool,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SandboxIdGenerateToolMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SandboxIdGenerateTool>>>
    
    export type PostApiV1SandboxIdGenerateToolMutationError = AxiosError<VirshSandboxInternalRestErrorResponse | VirshSandboxInternalRestGenerateResponse>

    /**
 * @summary Generate configuration
 */
export const usePostApiV1SandboxIdGenerateTool = <TError = AxiosError<VirshSandboxInternalRestErrorResponse | VirshSandboxInternalRestGenerateResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdGenerateTool>>, TError,{id: string;tool: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SandboxIdGenerateTool>>,
        TError,
        {id: string;tool: string},
        TContext
      > => {

      const mutationOptions = getPostApiV1SandboxIdGenerateToolMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Publishes sandbox changes to GitOps repository
 * @summary Publish changes
 */
export const postApiV1SandboxIdPublish = (
    id: string,
    virshSandboxInternalRestPublishRequest: VirshSandboxInternalRestPublishRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/v1/sandbox/${id}/publish`,
      virshSandboxInternalRestPublishRequest,options
    );
  }



export const getPostApiV1SandboxIdPublishMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse | VirshSandboxInternalRestPublishResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdPublish>>, TError,{id: string;data: VirshSandboxInternalRestPublishRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdPublish>>, TError,{id: string;data: VirshSandboxInternalRestPublishRequest}, TContext> => {

const mutationKey = ['postApiV1SandboxIdPublish'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SandboxIdPublish>>, {id: string;data: VirshSandboxInternalRestPublishRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SandboxIdPublish(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SandboxIdPublishMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SandboxIdPublish>>>
    export type PostApiV1SandboxIdPublishMutationBody = VirshSandboxInternalRestPublishRequest
    export type PostApiV1SandboxIdPublishMutationError = AxiosError<VirshSandboxInternalRestErrorResponse | VirshSandboxInternalRestPublishResponse>

    /**
 * @summary Publish changes
 */
export const usePostApiV1SandboxIdPublish = <TError = AxiosError<VirshSandboxInternalRestErrorResponse | VirshSandboxInternalRestPublishResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdPublish>>, TError,{id: string;data: VirshSandboxInternalRestPublishRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SandboxIdPublish>>,
        TError,
        {id: string;data: VirshSandboxInternalRestPublishRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1SandboxIdPublishMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Executes a command inside the sandbox via SSH
 * @summary Run command in sandbox
 */
export const postApiV1SandboxIdRun = (
    id: string,
    virshSandboxInternalRestRunCommandRequest: VirshSandboxInternalRestRunCommandRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VirshSandboxInternalRestRunCommandResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/sandbox/${id}/run`,
      virshSandboxInternalRestRunCommandRequest,options
    );
  }



export const getPostApiV1SandboxIdRunMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdRun>>, TError,{id: string;data: VirshSandboxInternalRestRunCommandRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdRun>>, TError,{id: string;data: VirshSandboxInternalRestRunCommandRequest}, TContext> => {

const mutationKey = ['postApiV1SandboxIdRun'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SandboxIdRun>>, {id: string;data: VirshSandboxInternalRestRunCommandRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SandboxIdRun(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SandboxIdRunMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SandboxIdRun>>>
    export type PostApiV1SandboxIdRunMutationBody = VirshSandboxInternalRestRunCommandRequest
    export type PostApiV1SandboxIdRunMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Run command in sandbox
 */
export const usePostApiV1SandboxIdRun = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdRun>>, TError,{id: string;data: VirshSandboxInternalRestRunCommandRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SandboxIdRun>>,
        TError,
        {id: string;data: VirshSandboxInternalRestRunCommandRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1SandboxIdRunMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a snapshot of the sandbox
 * @summary Create snapshot
 */
export const postApiV1SandboxIdSnapshot = (
    id: string,
    virshSandboxInternalRestSnapshotRequest: VirshSandboxInternalRestSnapshotRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VirshSandboxInternalRestSnapshotResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/sandbox/${id}/snapshot`,
      virshSandboxInternalRestSnapshotRequest,options
    );
  }



export const getPostApiV1SandboxIdSnapshotMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdSnapshot>>, TError,{id: string;data: VirshSandboxInternalRestSnapshotRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdSnapshot>>, TError,{id: string;data: VirshSandboxInternalRestSnapshotRequest}, TContext> => {

const mutationKey = ['postApiV1SandboxIdSnapshot'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SandboxIdSnapshot>>, {id: string;data: VirshSandboxInternalRestSnapshotRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SandboxIdSnapshot(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SandboxIdSnapshotMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SandboxIdSnapshot>>>
    export type PostApiV1SandboxIdSnapshotMutationBody = VirshSandboxInternalRestSnapshotRequest
    export type PostApiV1SandboxIdSnapshotMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Create snapshot
 */
export const usePostApiV1SandboxIdSnapshot = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdSnapshot>>, TError,{id: string;data: VirshSandboxInternalRestSnapshotRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SandboxIdSnapshot>>,
        TError,
        {id: string;data: VirshSandboxInternalRestSnapshotRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1SandboxIdSnapshotMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Injects a public SSH key for a user in the sandbox
 * @summary Inject SSH key into sandbox
 */
export const postApiV1SandboxIdSshkey = (
    id: string,
    virshSandboxInternalRestInjectSSHKeyRequest: VirshSandboxInternalRestInjectSSHKeyRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/v1/sandbox/${id}/sshkey`,
      virshSandboxInternalRestInjectSSHKeyRequest,options
    );
  }



export const getPostApiV1SandboxIdSshkeyMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdSshkey>>, TError,{id: string;data: VirshSandboxInternalRestInjectSSHKeyRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdSshkey>>, TError,{id: string;data: VirshSandboxInternalRestInjectSSHKeyRequest}, TContext> => {

const mutationKey = ['postApiV1SandboxIdSshkey'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SandboxIdSshkey>>, {id: string;data: VirshSandboxInternalRestInjectSSHKeyRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SandboxIdSshkey(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SandboxIdSshkeyMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SandboxIdSshkey>>>
    export type PostApiV1SandboxIdSshkeyMutationBody = VirshSandboxInternalRestInjectSSHKeyRequest
    export type PostApiV1SandboxIdSshkeyMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Inject SSH key into sandbox
 */
export const usePostApiV1SandboxIdSshkey = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdSshkey>>, TError,{id: string;data: VirshSandboxInternalRestInjectSSHKeyRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SandboxIdSshkey>>,
        TError,
        {id: string;data: VirshSandboxInternalRestInjectSSHKeyRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1SandboxIdSshkeyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Starts the virtual machine sandbox
 * @summary Start sandbox
 */
export const postApiV1SandboxIdStart = (
    id: string,
    virshSandboxInternalRestStartSandboxRequest: VirshSandboxInternalRestStartSandboxRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VirshSandboxInternalRestStartSandboxResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/sandbox/${id}/start`,
      virshSandboxInternalRestStartSandboxRequest,options
    );
  }



export const getPostApiV1SandboxIdStartMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdStart>>, TError,{id: string;data: VirshSandboxInternalRestStartSandboxRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdStart>>, TError,{id: string;data: VirshSandboxInternalRestStartSandboxRequest}, TContext> => {

const mutationKey = ['postApiV1SandboxIdStart'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SandboxIdStart>>, {id: string;data: VirshSandboxInternalRestStartSandboxRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SandboxIdStart(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SandboxIdStartMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SandboxIdStart>>>
    export type PostApiV1SandboxIdStartMutationBody = VirshSandboxInternalRestStartSandboxRequest
    export type PostApiV1SandboxIdStartMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Start sandbox
 */
export const usePostApiV1SandboxIdStart = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxIdStart>>, TError,{id: string;data: VirshSandboxInternalRestStartSandboxRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SandboxIdStart>>,
        TError,
        {id: string;data: VirshSandboxInternalRestStartSandboxRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1SandboxIdStartMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a new virtual machine sandbox from a base image
 * @summary Create a new sandbox
 */
export const postApiV1SandboxCreate = (
    virshSandboxInternalRestCreateSandboxRequest: VirshSandboxInternalRestCreateSandboxRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VirshSandboxInternalRestCreateSandboxResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/sandbox/create`,
      virshSandboxInternalRestCreateSandboxRequest,options
    );
  }



export const getPostApiV1SandboxCreateMutationOptions = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxCreate>>, TError,{data: VirshSandboxInternalRestCreateSandboxRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxCreate>>, TError,{data: VirshSandboxInternalRestCreateSandboxRequest}, TContext> => {

const mutationKey = ['postApiV1SandboxCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SandboxCreate>>, {data: VirshSandboxInternalRestCreateSandboxRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SandboxCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SandboxCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SandboxCreate>>>
    export type PostApiV1SandboxCreateMutationBody = VirshSandboxInternalRestCreateSandboxRequest
    export type PostApiV1SandboxCreateMutationError = AxiosError<VirshSandboxInternalRestErrorResponse>

    /**
 * @summary Create a new sandbox
 */
export const usePostApiV1SandboxCreate = <TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SandboxCreate>>, TError,{data: VirshSandboxInternalRestCreateSandboxRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SandboxCreate>>,
        TError,
        {data: VirshSandboxInternalRestCreateSandboxRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1SandboxCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    